{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow.fullname" . }}-secret
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ required "keycloak.clientSecret is required" .Values.keycloak.clientSecret | quote }}
  langflow-secret-key: {{ required "langflow.secretKey is required" .Values.langflow.secretKey | quote }}
{{- end }}
