apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow.fullname" . }}
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "langflow.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 7860
