"""Changed job_id in JobTable to be UUID instead of string

Revision ID: 00e5ef437a72
Revises: dd3dd875cd97
Create Date: 2026-01-25 21:32:44.515850

Phase: MIGRATE
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00e5ef437a72"  # pragma: allowlist secret
down_revision: str | None = "dd3dd875cd97"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.VARCHAR(), type_=sa.Uuid(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.Uuid(), type_=sa.VARCHAR(), existing_nullable=False)

    # ### end Alembic commands ###
