"""add_component_mappings_and_runtime_adapters

Revision ID: 0a08019dc5cc
Revises: d37bc4322900
Create Date: 2025-10-16 18:52:36.512193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '0a08019dc5cc'
down_revision: Union[str, None] = 'd37bc4322900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def enum_exists(name, conn):
    """Check if an enum type exists in PostgreSQL.

    Parameters:
    name (str): The name of the enum type to check.
    conn (sqlalchemy.engine.Engine or sqlalchemy.engine.Connection): The SQLAlchemy engine or connection to use.

    Returns:
    bool: True if the enum exists, False otherwise.
    """
    result = conn.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = :enum_name)"),
        {"enum_name": name}
    )
    return result.scalar()


def get_enum_values(name, conn):
    """Get the current values of an enum type in PostgreSQL.

    Parameters:
    name (str): The name of the enum type.
    conn (sqlalchemy.engine.Engine or sqlalchemy.engine.Connection): The SQLAlchemy engine or connection to use.

    Returns:
    list: List of enum values, or empty list if enum doesn't exist.
    """
    result = conn.execute(
        sa.text("""
            SELECT enumlabel
            FROM pg_type t
            JOIN pg_enum e ON t.oid = e.enumtypid
            WHERE typname = :enum_name
            ORDER BY enumsortorder
        """),
        {"enum_name": name}
    )
    return [row[0] for row in result.fetchall()]


def drop_enum_if_exists(name, conn):
    """Drop an enum type if it exists in PostgreSQL.

    Parameters:
    name (str): The name of the enum type to drop.
    conn (sqlalchemy.engine.Engine or sqlalchemy.engine.Connection): The SQLAlchemy engine or connection to use.
    """
    if enum_exists(name, conn):
        conn.execute(sa.text(f"DROP TYPE {name}"))
        conn.commit()


def upgrade() -> None:
    conn = op.get_bind()

    # Clean up any existing runtimetypeenum to avoid conflicts
    # SQLAlchemy will create it automatically during table creation
    if enum_exists('runtimetypeenum', conn):
        try:
            drop_enum_if_exists('runtimetypeenum', conn)
        except Exception:
            # If we can't drop it, continue - SQLAlchemy will handle the conflict
            pass

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_mappings',
    sa.Column('genesis_type', sa.String(length=100), nullable=False),
    sa.Column('base_config', sa.JSON(), nullable=True),
    sa.Column('io_mapping', sa.JSON(), nullable=True),
    sa.Column('component_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('healthcare_metadata', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tool_capabilities', sa.JSON(), nullable=True),
    sa.Column('runtime_introspection', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),  # New column for variant consolidation
    sa.Column('introspection_data', sa.JSON(), nullable=True),  # New column for introspection metadata
    sa.Column('introspected_at', sa.DateTime(), nullable=True),  # New column for introspection timestamp
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_category_active', ['component_category', 'active'], unique=False)
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_genesis_type_active', ['genesis_type', 'active'], unique=False)
        batch_op.create_index('idx_version_active', ['version', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_mappings_genesis_type'), ['genesis_type'], unique=False)

    op.create_table('runtime_adapters',
    sa.Column('runtime_type', sa.Enum('langflow', 'temporal', 'kafka', 'airflow', 'dagster', name='runtimetypeenum'), nullable=False),
    sa.Column('genesis_type', sa.String(length=100), nullable=False),
    sa.Column('target_component', sa.String(length=100), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('compliance_rules', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_adapters', schema=None) as batch_op:
        batch_op.create_index('idx_genesis_runtime_active', ['genesis_type', 'runtime_type', 'active'], unique=False)
        batch_op.create_index('idx_priority_active', ['priority', 'active'], unique=False)
        batch_op.create_index('idx_runtime_active', ['runtime_type', 'active'], unique=False)
        batch_op.create_index('idx_target_component', ['target_component'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_adapters_genesis_type'), ['genesis_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runtime_adapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_adapters_genesis_type'))
        batch_op.drop_index('idx_target_component')
        batch_op.drop_index('idx_runtime_active')
        batch_op.drop_index('idx_priority_active')
        batch_op.drop_index('idx_genesis_runtime_active')

    op.drop_table('runtime_adapters')
    with op.batch_alter_table('component_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_mappings_genesis_type'))
        batch_op.drop_index('idx_version_active')
        batch_op.drop_index('idx_genesis_type_active')
        batch_op.drop_index('idx_created_at')
        batch_op.drop_index('idx_category_active')

    op.drop_table('component_mappings')

    # Drop the runtime type enum if it exists
    if enum_exists('runtimetypeenum', conn):
        drop_enum_if_exists('runtimetypeenum', conn)

    # ### end Alembic commands ###
