"""Update description columns type

Revision ID: 348db7b74bee
Revises: 9f48c6c2f8dd
Create Date: 2024-10-08 11:17:55.340159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '348db7b74bee'
down_revision: Union[str, None] = '9f48c6c2f8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vertex_build')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vertex_build',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('artifacts', sqlite.JSON(), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('valid', sa.BOOLEAN(), nullable=False),
    sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
    sa.Column('build_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('build_id')
    )
    # ### end Alembic commands ###
