"""add deployment table

Revision ID: 4c72488864c6
Revises: 7d327cfafab6
Create Date: 2026-02-26 00:47:43.856001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '4c72488864c6'
down_revision: Union[str, None] = '7d327cfafab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['provider_account_id'], ['deployment_provider_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_deployment_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_provider_account_id'), ['provider_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_resource_key'), ['resource_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_user_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_resource_key'))
        batch_op.drop_index(batch_op.f('ix_deployment_provider_account_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_name'))

    op.drop_table('deployment')
    # ### end Alembic commands ###
