"""Add category column to variable table, to support models.

Revision ID: 50bdbf646c1c
Revises: 3162e83e485f
Create Date: 2025-08-13 13:36:47.517609

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50bdbf646c1c"
down_revision: str | None = "3162e83e485f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore[arg-type]
    column_names = [column["name"] for column in inspector.get_columns("variable")]
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("variable", schema=None) as batch_op:
        if "category" not in column_names:
            batch_op.add_column(sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore[arg-type]
    column_names = [column["name"] for column in inspector.get_columns("variable")]
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("variable", schema=None) as batch_op:
        if "category" in column_names:
            batch_op.drop_column("category")

    # ### end Alembic commands ###
