"""add flow_version table, and latest_version column to flow table
Migration: Add flow_version table and latest_version column to flow table
Phase: EXPAND
Revision ID: 7a29e839692d
Revises: 182e5471b900
Create Date: 2026-01-01 02:34:06.352999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '7a29e839692d'
down_revision: Union[str, None] = '182e5471b900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('flow_data', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'version', name='unique_flow_version'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('flow_version', schema=None) as batch_op:
        batch_op.create_index('flow_version_index', ['flow_id', 'version'], unique=False)

    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_version', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.drop_column('latest_version')

    with op.batch_alter_table('flow_version', schema=None) as batch_op:
        batch_op.drop_index('flow_version_index')

    op.drop_table('flow_version')
    # ### end Alembic commands ###
