"""adding_ingestion_relations_to_messages

Phase: EXPAND

Revision ID: 7dfcd1cfd6c9
Revises: d1e2f3a4b5c6
Create Date: 2026-04-02 16:47:50.918307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '7dfcd1cfd6c9'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingestion_job_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('ingestion_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('ingestion_timestamp')
        batch_op.drop_column('ingestion_job_id')

    # ### end Alembic commands ###
