"""Add package installation table.

Revision ID: 8693956d355f
Revises: 3162e83e485f
Create Date: 2025-07-28 09:56:58.645226

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from langflow.utils import migration

# revision identifiers, used by Alembic.
revision: str = "8693956d355f"
down_revision: str | None = "3162e83e485f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    if not migration.table_exists("packageinstallation", conn):
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
            "packageinstallation",
            sa.Column("package_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "status",
                sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="installationstatus"),
                nullable=False,
            ),
            sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column(
                "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
            ),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if migration.table_exists("packageinstallation", conn):
        op.drop_table("packageinstallation")
    # ### end Alembic commands ###
