"""Add column for github to Flow

Revision ID: 8f91d97e805a
Revises: f3b2d1f1002d
Create Date: 2025-03-18 12:13:42.855426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '8f91d97e805a'
down_revision: Union[str, None] = 'f3b2d1f1002d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    # ### commands auto generated by Alembic - please adjust! ###
    column_names = [column["name"] for column in inspector.get_columns("flow")]
    with op.batch_alter_table("flow", schema=None) as batch_op:
        if "git_repo" not in column_names:
            batch_op.add_column(sa.Column("git_repo", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if "git_branch" not in column_names:
            batch_op.add_column(sa.Column("git_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if "git_file_path" not in column_names:
            batch_op.add_column(sa.Column("git_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if "github_api_token" not in column_names:
            batch_op.add_column(sa.Column("github_api_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        if "github_sha" not in column_names:
            batch_op.add_column(sa.Column("github_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    column_names = [column["name"] for column in inspector.get_columns("flow")]
    with op.batch_alter_table("flow", schema=None) as batch_op:
        if "github_sha" in column_names:
            batch_op.drop_column("github_sha")
        if "github_api_token" in column_names:
            batch_op.drop_column("github_api_token")
        if "git_file_path" in column_names:
            batch_op.drop_column("git_file_path")
        if "git_branch" in column_names:
            batch_op.drop_column("git_branch")
        if "git_repo" in column_names:
            batch_op.drop_column("git_repo")

    # ### end Alembic commands ###
