"""remove file table

Revision ID: a4d8dc9740c0
Revises: f3b2d1f1002d
Create Date: 2024-03-18 09:49:32.264341

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'a4d8dc9740c0'
down_revision: Union[str, None] = 'f3b2d1f1002d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    if "file" in table_names:
        try:
            op.drop_table('file')
        except Exception as e:
            print(e)
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    if "file" not in table_names:
        try:
            op.create_table('file',
                sa.Column('id', sa.CHAR(length=32), nullable=False),
                sa.Column('user_id', sa.CHAR(length=32), nullable=False),
                sa.Column('name', sa.VARCHAR(), nullable=False),
                sa.Column('path', sa.VARCHAR(), nullable=False),
                sa.Column('size', sa.INTEGER(), nullable=False),
                sa.Column('provider', sa.VARCHAR(), nullable=True),
                sa.Column('created_at', sa.DATETIME(), nullable=False),
                sa.Column('updated_at', sa.DATETIME(), nullable=False),
                sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_file_user_id_user'),
                sa.PrimaryKeyConstraint('id'),
                sa.UniqueConstraint('name')
            )
        except Exception as e:
            print(e)
            pass
    # ### end Alembic commands ###
