"""add cron_expression col

Revision ID: a5c648dd7ad6
Revises: 318889d49162
Create Date: 2024-10-07 16:36:26.665898

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import sqlite
from sqlalchemy.engine.reflection import Inspector

from langflow.utils import migration

# revision identifiers, used by Alembic.
revision: str = 'a5c648dd7ad6'
down_revision: Union[str, None] = '318889d49162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        if not migration.column_exists(conn=conn, table_name="task", column_name="cron_expression"):
            batch_op.add_column(sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        if migration.column_exists(conn=conn, table_name="task", column_name="cron_expression"):
            batch_op.drop_column('cron_expression')

        # ### end Alembic commands ###
