"""add cron_expression col

Revision ID: a5c648dd7ad6
Revises: 318889d49162
Create Date: 2024-10-07 16:36:26.665898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a5c648dd7ad6'
down_revision: Union[str, None] = '318889d49162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vertex_build')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('cron_expression')

    op.create_table('vertex_build',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('artifacts', sqlite.JSON(), nullable=True),
    sa.Column('params', sa.VARCHAR(), nullable=True),
    sa.Column('build_id', sa.CHAR(length=32), nullable=False),
    sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
    sa.Column('valid', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name='fk_vertex_build_flow_id'),
    sa.PrimaryKeyConstraint('build_id')
    )
    # ### end Alembic commands ###
