"""create components table

Revision ID: b05879ebbca2
Revises: 1cb603706752
Create Date: 2025-08-26 17:19:06.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'b05879ebbca2'
down_revision: Union[str, None] = '0882f9657f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    existing_tables = inspector.get_table_names()
    
    if "components" not in existing_tables:
        op.create_table('components',
        sa.Column('id', sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
        sa.Column('component_path', sa.String(), nullable=False),
        sa.Column('folder', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('code', sa.Text(), nullable=False),
        sa.Column('signature', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('folder', 'component_path', 'version', name='uq_folder_component_version')
        )
        op.create_index(op.f('ix_components_component_path'), 'components', ['component_path'], unique=False)
        op.create_index(op.f('ix_components_folder'), 'components', ['folder'], unique=False)
        op.create_index(op.f('ix_components_version'), 'components', ['version'], unique=False)
        op.create_index('idx_components_signature', 'components', ['signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    existing_tables = inspector.get_table_names()
    
    if "components" in existing_tables:
        op.drop_index(op.f('ix_components_component_path'), table_name='components')
        op.drop_index(op.f('ix_components_folder'), table_name='components')
        op.drop_index(op.f('ix_components_version'), table_name='components')
        op.drop_index('idx_components_signature', table_name='components')
        op.drop_table('components')
    # ### end Alembic commands ###