"""Fixes Private variable issue

Revision ID: b53514fbde6e
Revises: f3b2d1f1002d
Create Date: 2025-03-18 21:14:44.863704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'b53514fbde6e'
down_revision: Union[str, None] = 'f3b2d1f1002d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
