"""Changed job_id in vertex_build table to be UUID instead of str.

Revision ID: dd3dd875cd97
Revises: f7a564a956a8
Create Date: 2026-01-25 20:23:02.795268

Phase: MIGRATE
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd3dd875cd97"
down_revision: str | None = "f7a564a956a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.VARCHAR(), type_=sa.Uuid(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.Uuid(), type_=sa.VARCHAR(), existing_nullable=True)

    # ### end Alembic commands ###
