"""Update description columns type Errors

Revision ID: e4aaf16201c2
Revises: 0ae3a2674f32
Create Date: 2024-10-08 11:45:03.537278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite
from langflow.utils.migration import table_exists

# revision identifiers, used by Alembic.
revision: str = 'e4aaf16201c2'
down_revision: Union[str, None] = '0ae3a2674f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('vertex_build', conn):
        op.drop_table('vertex_build')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('vertex_build', conn):
        op.create_table('vertex_build',
        sa.Column('timestamp', sa.DATETIME(), nullable=False),
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('data', sqlite.JSON(), nullable=True),
        sa.Column('artifacts', sqlite.JSON(), nullable=True),
        sa.Column('params', sa.TEXT(), nullable=True),
        sa.Column('valid', sa.BOOLEAN(), nullable=False),
        sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
        sa.Column('build_id', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
        sa.PrimaryKeyConstraint('build_id')
        )
    # ### end Alembic commands ###
