"""add status column in flow

Revision ID: ea8c52f13171
Revises: 66f72f04a1de
Create Date: 2025-05-07 14:30:49.260805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'ea8c52f13171'
down_revision: Union[str, None] = '66f72f04a1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow', schema=None) as batch_op:
        if not migration.column_exists(table_name="flow", column_name="status", conn=conn):
            batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'DEPLOYED', name='deployment_state_enum'), server_default=sa.text("'DRAFT'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow', schema=None) as batch_op:
        if migration.column_exists(table_name="flow", column_name="status", conn=conn):
            batch_op.drop_column('status')

    # ### end Alembic commands ###
