"""Add error and edit flags to message

Revision ID: eb5e72293a8e
Revises: e5a65ecff2cd
Create Date: 2024-09-19 16:18:50.828648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'eb5e72293a8e'
down_revision: Union[str, None] = 'e5a65ecff2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Boolean(), nullable=False, server_default='False'))
        batch_op.add_column(sa.Column('edit', sa.Boolean(), nullable=False, server_default='False'))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('edit')
        batch_op.drop_column('error')

    # ### end Alembic commands ###
