# Azure DevOps Pipeline for AI Studio Backend
# Triggers on backend-related changes in the monorepo

resources:
  repositories:
  - repository: platform-charts
    type: github
    endpoint: autonomize-ai
    name: autonomize-ai/platform-charts
    ref: main

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
  paths:
    include:
      - src/backend/**
      - pyproject.toml
      - uv.lock
      - docker/backend/**
      - azure-devops/pipelines/azure-pipelines-backend.yml

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/backend/**
      - pyproject.toml
      - uv.lock
      - docker/backend/**
      - azure-devops/pipelines/azure-pipelines-backend.yml

variables:
  # Container Registry Configuration
  ACR_NAME: 'sprintregistry'
  ACR_ENDPOINT: 'sprintregistry.azurecr.io'
  IMAGE_NAME: 'ai-studio-backend'
  DOCKERFILE_PATH: 'docker/backend/Dockerfile'

  # Python Configuration
  PYTHON_VERSION: '3.12'
  UV_VERSION: '0.4.0'

  # Build Configuration
  BUILD_CONFIGURATION: 'Release'
  WORKING_DIRECTORY: 'src/backend'

  # Platform Charts Configuration
  VALUES_FILE: 'charts/genesis-platform/values-dev.yaml'

stages:
  - stage: Test
    displayName: 'Test and Validate Backend'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: RunBackendTests
        displayName: 'Run Backend Tests and Linting'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(PYTHON_VERSION)
            displayName: 'Set up Python $(PYTHON_VERSION)'

          - script: |
              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="$HOME/.cargo/bin:$PATH"
              uv --version
            displayName: 'Install UV Package Manager'

          - script: |
              export PATH="$HOME/.cargo/bin:$PATH"
              uv sync --frozen
              echo "Dependencies installed successfully"
            displayName: 'Install Dependencies'

          - script: |
              export PATH="$HOME/.cargo/bin:$PATH"
              uv run python -m pytest src/backend/tests/ -v --tb=short || echo "Running available tests"
            displayName: 'Run Backend Tests'

          - script: |
              export PATH="$HOME/.cargo/bin:$PATH"
              uv run ruff check src/backend/ || echo "Ruff linting completed"
              uv run ruff format --check src/backend/ || echo "Format check completed"
            displayName: 'Lint Backend Code'

          - script: |
              export PATH="$HOME/.cargo/bin:$PATH"
              cd src/backend && python test_genesis_direct.py
            displayName: 'Run Genesis Module Tests'

  - stage: Build
    displayName: 'Build and Push Backend Docker Image'
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/develop'))
    jobs:
      - job: BuildAndPushBackendImage
        displayName: 'Build and Push Backend to ACR'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build Backend Docker Image'
            inputs:
              command: 'build'
              repository: $(IMAGE_NAME)
              containerRegistry: $(ACR_NAME)
              dockerfile: $(DOCKERFILE_PATH)
              buildContext: '.'
              arguments: |
                --build-arg BUILD_VERSION=$(Build.BuildId)
                --build-arg PYTHON_VERSION=$(PYTHON_VERSION)
              tags: |
                $(Build.BuildId)
                latest

          - task: Docker@2
            displayName: 'Push Backend Image to Registry'
            inputs:
              command: 'push'
              repository: $(IMAGE_NAME)
              containerRegistry: $(ACR_NAME)
              tags: |
                $(Build.BuildId)
                latest

  - stage: UpdatePlatformCharts
    displayName: 'Update Platform Charts Image Tags'
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/develop'))
    dependsOn: Build
    jobs:
      - job: UpdateImageTags
        displayName: 'Update Backend Image Tags in Platform Charts'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: platform-charts
            fetchDepth: 0
            persistCredentials: true

          - script: |
              git config --global user.email "release@autonomize.ai"
              git config --global user.name "release"
              git checkout main
            displayName: 'Setup GIT'

          - script: |
              echo "Build Number: $(Build.BuildId)"
              wget -q https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64
              mv yq_linux_amd64 /usr/local/bin/yq
              chmod +x /usr/local/bin/yq

              # Update umbrella chart values
              echo "Updating backend image tag in umbrella chart..."
              buildnumber="$(Build.BuildId)" yq -i e '.ai-studio.backend.image.tag = env(buildnumber)' $(VALUES_FILE)

              # Show the changes
              echo "=== Changes Made ==="
              git diff
            displayName: 'Update Image Tags'

          - script: |
              git add $(VALUES_FILE)
              git commit -m "[skip ci] Backend image tag updated: $(Build.BuildId) in platform-charts" || echo "No changes to commit"
              git push --set-upstream origin main

              echo "✅ Platform charts updated with backend image tag: $(Build.BuildId)"
            displayName: 'Push version to git'

  - stage: SecurityScan
    displayName: 'Security and Vulnerability Scanning'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: UpdatePlatformCharts
    jobs:
      - job: ContainerScan
        displayName: 'Scan Backend Container for Vulnerabilities'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: CmdLine@2
            displayName: 'Run Trivy Security Scan'
            inputs:
              script: |
                # Install Trivy
                sudo apt-get update
                sudo apt-get install wget apt-transport-https gnupg lsb-release
                wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
                echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
                sudo apt-get update
                sudo apt-get install trivy

                # Scan the image
                trivy image --exit-code 0 --severity HIGH,CRITICAL $(ACR_ENDPOINT)/$(IMAGE_NAME):$(Build.BuildId) || echo "Security scan completed with warnings"
            continueOnError: true

  - stage: Notification
    displayName: 'Send Build Notifications'
    condition: always()
    dependsOn:
      - Test
      - Build
      - UpdatePlatformCharts
      - SecurityScan
    jobs:
      - job: NotifyBackendCompletion
        displayName: 'Backend Pipeline Completion Notification'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "🔧 AI Studio Backend Pipeline Completed"
              echo "Build ID: $(Build.BuildId)"
              echo "Source Branch: $(Build.SourceBranch)"
              echo "Commit: $(Build.SourceVersion)"
              echo "Trigger: $(Build.Reason)"

              if [ "$(Agent.JobStatus)" == "Succeeded" ]; then
                echo "✅ Backend pipeline succeeded!"
                echo "🐳 Docker Image: $(ACR_ENDPOINT)/$(IMAGE_NAME):$(Build.BuildId)"
                echo "📦 Platform Charts Updated: AI Studio Backend"
                echo "🚀 ArgoCD will detect changes and deploy automatically"
              else
                echo "❌ Backend pipeline failed or was partially successful"
              fi

              echo "📊 Backend Components:"
              echo "  - Genesis Spec System"
              echo "  - Langflow Components"
              echo "  - AI Studio APIs"
              echo "  - Healthcare Components"
            displayName: 'Backend Pipeline Summary'