#! /bin/bash

docker build -t logspace/frontend_build -f build.Dockerfile .
poetry remove langchain
VERSION=$(toml get --toml-path pyproject.toml tool.poetry.version)
docker build --build-arg VERSION=$VERSION -t ibiscp/langflow:$VERSION . && docker push ibiscp/langflow:$VERSION
poetry add --editable ../../../langchain
