#!/usr/bin/env python3
"""
Test script to verify the PostgreSQL auto-migration fix
"""
import asyncio
import os
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected, CommandError
from sqlalchemy import create_engine, text
from sqlalchemy.ext.asyncio import create_async_engine

# Add the source path so we can import langflow modules
import sys
sys.path.insert(0, str(Path(__file__).parent / "src" / "backend" / "base"))

from langflow.services.database.service import DatabaseService
from langflow.services.settings.service import SettingsService


class TestDatabaseService:
    """Test the database migration logic"""

    def setup_method(self):
        """Setup test environment"""
        # Create temporary directory for test database
        self.temp_dir = tempfile.mkdtemp()
        self.sqlite_url = f"sqlite:///{self.temp_dir}/test.db"
        self.postgres_url = "postgresql://postgres:postgres@localhost:5432/test_migrations"

    def teardown_method(self):
        """Cleanup after tests"""
        import shutil
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_sqlite_migration_success(self):
        """Test that SQLite migrations work correctly"""
        # Mock settings service
        with patch('langflow.services.settings.service.SettingsService') as mock_settings_service:
            mock_settings = mock_settings_service.return_value
            mock_settings.settings.database_url = self.sqlite_url
            mock_settings.settings.alembic_log_file = "test_alembic.log"
            mock_settings.settings.database_connection_retry = False
            mock_settings.settings.sqlite_pragmas = {}

            # Create database service
            db_service = DatabaseService(mock_settings)

            # Test migration initialization
            try:
                # This should work without raising exceptions
                with tempfile.NamedTemporaryFile(mode='w', suffix='.log') as log_file:
                    db_service.alembic_log_path = Path(log_file.name)
                    db_service._run_migrations(should_initialize_alembic=True, fix=False)
                    print("✅ SQLite migration test passed")
            except Exception as e:
                print(f"❌ SQLite migration test failed: {e}")
                raise

    def test_postgres_migration_with_mock_autodiff(self):
        """Test PostgreSQL with mocked AutogenerateDiffsDetected exception"""
        # Mock settings service
        with patch('langflow.services.settings.service.SettingsService') as mock_settings_service:
            mock_settings = mock_settings_service.return_value
            mock_settings.settings.database_url = self.postgres_url
            mock_settings.settings.alembic_log_file = "test_alembic.log"
            mock_settings.settings.database_connection_retry = False
            mock_settings.settings.db_connection_settings = {}
            mock_settings.settings.db_driver_connection_settings = None

            # Create database service
            db_service = DatabaseService(mock_settings)

            # Test with mocked AutogenerateDiffsDetected exception
            with patch('alembic.command.check') as mock_check, \
                 patch('alembic.command.upgrade') as mock_upgrade, \
                 tempfile.NamedTemporaryFile(mode='w', suffix='.log') as log_file:

                db_service.alembic_log_path = Path(log_file.name)

                # First call raises AutogenerateDiffsDetected, second call succeeds
                mock_check.side_effect = [
                    AutogenerateDiffsDetected("Schema differences detected"),
                    None  # Second call after upgrade succeeds
                ]

                try:
                    db_service._run_migrations(should_initialize_alembic=False, fix=False)
                    print("✅ PostgreSQL auto-upgrade test passed")

                    # Verify upgrade was called
                    mock_upgrade.assert_called_once()
                    print("✅ Auto-upgrade was triggered correctly")

                except Exception as e:
                    print(f"❌ PostgreSQL auto-upgrade test failed: {e}")
                    raise

    def test_command_error_handling(self):
        """Test handling of CommandError exceptions"""
        with patch('langflow.services.settings.service.SettingsService') as mock_settings_service:
            mock_settings = mock_settings_service.return_value
            mock_settings.settings.database_url = self.sqlite_url
            mock_settings.settings.alembic_log_file = "test_alembic.log"
            mock_settings.settings.database_connection_retry = False
            mock_settings.settings.sqlite_pragmas = {}

            db_service = DatabaseService(mock_settings)

            with patch('alembic.command.check') as mock_check, \
                 patch('alembic.command.upgrade') as mock_upgrade, \
                 tempfile.NamedTemporaryFile(mode='w', suffix='.log') as log_file:

                db_service.alembic_log_path = Path(log_file.name)

                # Mock a CommandError that should trigger upgrade
                mock_check.side_effect = CommandError("AutogenerateDiffsDetected in revision")

                try:
                    db_service._run_migrations(should_initialize_alembic=False, fix=False)
                    print("✅ CommandError handling test passed")

                    # Verify upgrade was called
                    mock_upgrade.assert_called_once()
                    print("✅ Auto-upgrade triggered for CommandError correctly")

                except Exception as e:
                    print(f"❌ CommandError handling test failed: {e}")
                    raise


def test_database_url_sanitization():
    """Test that database URL sanitization works correctly"""
    with patch('langflow.services.settings.service.SettingsService') as mock_settings_service:
        mock_settings = mock_settings_service.return_value
        mock_settings.settings.alembic_log_file = "test_alembic.log"
        mock_settings.settings.database_connection_retry = False
        mock_settings.settings.sqlite_pragmas = {}

        # Test PostgreSQL URL sanitization
        mock_settings.settings.database_url = "postgresql://user:pass@localhost:5432/db"
        db_service = DatabaseService(mock_settings)
        assert db_service.database_url == "postgresql+psycopg://user:pass@localhost:5432/db"
        print("✅ PostgreSQL URL sanitization test passed")

        # Test SQLite URL sanitization
        mock_settings.settings.database_url = "sqlite:///test.db"
        db_service = DatabaseService(mock_settings)
        assert db_service.database_url == "sqlite+aiosqlite:///test.db"
        print("✅ SQLite URL sanitization test passed")


if __name__ == "__main__":
    print("🔄 Running migration fix tests...\n")

    # Test URL sanitization
    test_database_url_sanitization()
    print()

    # Test migration logic
    test_service = TestDatabaseService()

    print("Testing SQLite migration...")
    test_service.setup_method()
    try:
        test_service.test_sqlite_migration_success()
    finally:
        test_service.teardown_method()
    print()

    print("Testing PostgreSQL auto-upgrade with mock...")
    test_service.setup_method()
    try:
        test_service.test_postgres_migration_with_mock_autodiff()
    finally:
        test_service.teardown_method()
    print()

    print("Testing CommandError handling...")
    test_service.setup_method()
    try:
        test_service.test_command_error_handling()
    finally:
        test_service.teardown_method()
    print()

    print("✅ All migration fix tests completed successfully!")