"""initial lfx execution history schema

Revision ID: 35f161a1123e
Revises: 
Create Date: 2026-07-13 18:15:11.003221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '35f161a1123e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('edit', sa.Boolean(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content_blocks', sa.JSON(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('is_output', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_run_id'), ['run_id'], unique=False)

    op.create_table('transaction',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vertex_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vertex_build',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('build_id')
    )
    with op.batch_alter_table('vertex_build', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vertex_build_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vertex_build', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vertex_build_job_id'))

    op.drop_table('vertex_build')
    op.drop_table('transaction')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_run_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
