"""empty message

Revision ID: 0b8757876a7c
Revises: 006b3990db50
Create Date: 2024-01-17 10:32:56.686287

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b8757876a7c'
down_revision: Union[str, None] = '006b3990db50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('apikey', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_apikey_api_key'), ['api_key'], unique=True)
            batch_op.create_index(batch_op.f('ix_apikey_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_apikey_user_id'), ['user_id'], unique=False)
    except Exception as e:
        print(e)
        pass
    try:
        with op.batch_alter_table('flow', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_flow_description'), ['description'], unique=False)
            batch_op.create_index(batch_op.f('ix_flow_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_flow_user_id'), ['user_id'], unique=False)
    except Exception as e:
        print(e)
        pass

    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
    except Exception as e:
        print(e)
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_username'))
    except Exception as e:
        print(e)
        pass
    try:
        with op.batch_alter_table('flow', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_flow_user_id'))
            batch_op.drop_index(batch_op.f('ix_flow_name'))
            batch_op.drop_index(batch_op.f('ix_flow_description'))
    except Exception as e:
        print(e)
        pass
    try:
        with op.batch_alter_table('apikey', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_apikey_user_id'))
            batch_op.drop_index(batch_op.f('ix_apikey_name'))
            batch_op.drop_index(batch_op.f('ix_apikey_api_key'))
    except Exception as e:
        print(e)
        pass
    # ### end Alembic commands ###