"""Add Flow table

Revision ID: 4814b6f4abfd
Revises:
Create Date: 2023-08-05 17:47:42.879824

"""

import contextlib
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4814b6f4abfd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # This suppress is used to not break the migration if the table already exists.
    with contextlib.suppress(sa.exc.OperationalError):
        op.create_table(
            "flow",
            sa.Column("data", sa.JSON(), nullable=True),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("id"),
        )
        op.create_index(
            op.f("ix_flow_description"), "flow", ["description"], unique=False
        )
        op.create_index(op.f("ix_flow_name"), "flow", ["name"], unique=False)
    with contextlib.suppress(sa.exc.OperationalError):
        op.create_table(
            "flowstyle",
            sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("flow_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
            sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
            sa.ForeignKeyConstraint(
                ["flow_id"],
                ["flow.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flowstyle")
    op.drop_index(op.f("ix_flow_name"), table_name="flow")
    op.drop_index(op.f("ix_flow_description"), table_name="flow")
    op.drop_table("flow")
    # ### end Alembic commands ###
