export const MARKETPLACE_TAGS: { title: string; id: string, icon: string }[] = [
  { title: 'Patient Experience', id: 'patient-experience', icon: 'BotMessageSquare' },
  { title: 'Provider Enablement', id: 'provider-enablement', icon: 'BotMessageSquare' },
  { title: 'Utilization Management', id: 'utilization-management', icon: 'BotMessageSquare' },
  { title: 'Care Management', id: 'care-management', icon: 'BotMessageSquare' },
  { title: 'Risk Adjustment', id: 'risk-adjustment', icon: 'BotMessageSquare' },
  { title: 'Claims Operations', id: 'claims-operations', icon: 'BotMessageSquare' },
  { title: 'Contracting & RFP', id: 'contracting-rfp', icon: 'BotMessageSquare' },
  { title: 'Member Engagement', id: 'member-engagement', icon: 'BotMessageSquare' },
  { title: 'Population Health', id: 'population-health', icon: 'BotMessageSquare' },
  { title: 'Provider Data Management', id: 'provider-data-management', icon: 'BotMessageSquare' },
  { title: 'Actuarial', id: 'actuarial', icon: 'BotMessageSquare' },
  { title: 'Finance', id: 'finance', icon: 'BotMessageSquare' },
  { title: 'Compliance', id: 'compliance', icon: 'BotMessageSquare' },
  { title: 'Audit', id: 'audit', icon: 'BotMessageSquare' },
  { title: 'PBM', id: 'pbm', icon: 'BotMessageSquare' },
  { title: 'Pharmacy', id: 'pharmacy', icon: 'BotMessageSquare' },
  { title: 'Provider Ops', id: 'provider-ops', icon: 'BotMessageSquare' },
  { title: 'Provider Contracting', id: 'provider-contracting', icon: 'BotMessageSquare' },
  { title: 'Network Management', id: 'network-management', icon: 'BotMessageSquare' },
  { title: 'Appeals & Grievances', id: 'appeals-grievances', icon: 'BotMessageSquare' },
  { title: 'Quality', id: 'quality', icon: 'BotMessageSquare' },
  { title: 'Stars', id: 'stars', icon: 'BotMessageSquare' },
  { title: 'Revenue Cycle Management', id: 'revenue-cycle-management', icon: 'BotMessageSquare' },
  { title: 'Care Gap', id: 'care-gap', icon: 'BotMessageSquare' },
  { title: 'Chart Review', id: 'chart-review', icon: 'BotMessageSquare' },
  { title: 'Hedis Care Gap', id: 'hedis-care-gap', icon: 'BotMessageSquare' },
  { title: 'Clinical Research', id: 'clinical-research', icon: 'BotMessageSquare' },
] as const;

export type MarketplaceTag = typeof MARKETPLACE_TAGS[number]['title'];