CREDENTIAL_TYPE = "Credential"
GENERIC_TYPE = "Generic"

CATEGORY_GLOBAL = "Global"
CATEGORY_SETTINGS = "Settings"
CATEGORY_LLM = "LLM"

VALID_CATEGORIES = [CATEGORY_GLOBAL, CATEGORY_SETTINGS, CATEGORY_LLM]
