{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-studio.frontend.serviceAccountName" . }}
  labels:
    {{- include "ai-studio.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.automount | default true }}
{{- end }}

{{- if .Values.backend.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-studio.backend.serviceAccountName" . }}
  labels:
    {{- include "ai-studio.backend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.backend.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}