"""Schema converters for V2 Workflow API.

This module provides conversion functions between the new V2 workflow schemas
and the existing V1 schemas, enabling reuse of existing execution logic while
presenting a new API interface.

Key Functions:
    - parse_workflow_run_request: Parse the native WorkflowRunRequest body
    - run_response_to_workflow_response: Converts V1 RunResponse to V2 WorkflowExecutionResponse
    - create_error_response: Creates standardized error responses
    - create_job_response: Creates background job responses

Internal Helpers:
    - _extract_nested_value: Safely extracts nested values from dict/object structures
    - _extract_text_from_message: Extracts plain text from various message formats
    - _simplify_output_content: Simplifies output content based on type
    - _get_raw_content: Extracts raw content from vertex output data
    - _extract_model_source: Extracts model information from LLM outputs
    - _extract_file_path: Extracts file path from SaveToFile outputs
    - _build_metadata_for_non_output: Builds metadata for non-output terminal nodes
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

from lfx.schema.workflow import (
    ComponentOutput,
    ErrorDetail,
    JobId,
    JobStatus,
    OutputReason,
    WorkflowExecutionResponse,
    WorkflowJobResponse,
    WorkflowOutput,
    WorkflowRunRequest,
)

if TYPE_CHECKING:
    from lfx.graph.graph.base import Graph

    from langflow.api.v1.schemas import RunResponse


@dataclass(frozen=True)
class ParsedWorkflowRun:
    """Langflow run parameters extracted from a native ``WorkflowRunRequest``."""

    flow_id: str | None
    tweaks: dict[str, Any] = field(default_factory=dict)
    input_value: str = ""
    session_id: str | None = None
    run_id: str | None = None
    mode: str = "stream"
    start_component_id: str | None = None
    stop_component_id: str | None = None
    # Request-side output selection (sync mode): when set, the answer (``output``)
    # resolves among only these component ids. Validated against the flow's outputs
    # before the flow runs.
    output_ids: list[str] | None = None
    # Optional live flow data (nodes + edges) overriding the DB copy. Lets the
    # canvas run with unsaved tweaks the user has made but not yet persisted.
    data: dict[str, Any] | None = None
    # Optional runtime file references the graph build needs.
    files: list[str] | None = None
    # Request-level global variables from the JSON body (v2 body-globals).
    globals: dict[str, str] = field(default_factory=dict)


def parse_workflow_run_request(request: WorkflowRunRequest) -> ParsedWorkflowRun:
    """Extract Langflow run parameters from the native ``WorkflowRunRequest`` body.

    Every field on the request is first-class; no escape-hatch flattening of
    ``forwardedProps`` is needed. ``run_id`` is generated by the endpoint, not
    the caller, so it is left ``None`` here.

    Args:
        request: The v2 native body shape.

    Returns:
        ParsedWorkflowRun: the Langflow run parameters.
    """
    return ParsedWorkflowRun(
        flow_id=request.flow_id,
        tweaks=request.tweaks,
        input_value=request.input_value,
        session_id=request.session_id,
        run_id=None,
        mode=request.mode.value,
        start_component_id=request.start_component_id,
        stop_component_id=request.stop_component_id,
        output_ids=request.output_ids,
        data=request.data,
        files=request.files,
        globals=dict(request.globals or {}),
    )


def _extract_nested_value(data: Any, *keys: str) -> Any:
    """Safely extract nested value from dict-like structure.

    Args:
        data: The data structure to extract from
        *keys: Sequence of keys to traverse

    Returns:
        The extracted value or None if not found

    Example:
        >>> _extract_nested_value({'a': {'b': 'value'}}, 'a', 'b')
        'value'
    """
    current = data
    for key in keys:
        if isinstance(current, dict):
            current = current.get(key)
        elif hasattr(current, key):
            current = getattr(current, key)
        else:
            return None
        if current is None:
            return None
    return current


def _extract_text_from_message(content: dict) -> str | None:
    """Extract plain text from nested message structures.

    Handles various message formats by trying common paths in order:
    - {'message': {'message': 'text', 'type': 'text'}}
    - {'text': {'message': 'text'}}
    - {'message': {'text': 'text'}}
    - {'message': 'text'}
    - {'text': {'text': 'text'}}
    - {'text': 'text'}

    Args:
        content: The message content dict

    Returns:
        Extracted text string or None
    """
    paths = [
        ("message", "message"),
        ("text", "message"),
        ("message", "text"),
        ("message",),
        ("text", "text"),
        ("text",),
    ]
    for path in paths:
        text = _extract_nested_value(content, *path)
        if isinstance(text, str):
            return text
    return None


def _extract_model_source(raw_content: dict, vertex_id: str, vertex_display_name: str) -> dict | None:
    """Extract model source information from LLM component output.

    Args:
        raw_content: The raw output data
        vertex_id: Vertex ID
        vertex_display_name: Vertex display name

    Returns:
        Source info dict or None
    """
    model_name = _extract_nested_value(raw_content, "model_output", "message", "model_name")
    if model_name:
        return {"id": vertex_id, "display_name": vertex_display_name, "source": model_name}
    return None


def _extract_file_path(raw_content: dict, vertex_type: str) -> str | None:
    """Extract file path from SaveToFile component output.

    Args:
        raw_content: The raw output data
        vertex_type: The vertex type

    Returns:
        File path string or None
    """
    if vertex_type != "SaveToFile":
        return None

    # Extract the message from SaveToFile component
    # Return the whole message instead of filtering by specific wording
    file_msg = _extract_nested_value(raw_content, "message", "message")
    if isinstance(file_msg, str):
        return file_msg

    return None


def _get_raw_content(vertex_output_data: Any) -> Any:
    """Extract raw content from vertex output data.

    Tries multiple fields in order: outputs, results, messages.
    Note: Uses 'is not None' checks to avoid treating empty collections as missing.

    Args:
        vertex_output_data: The output data from RunResponse

    Returns:
        Raw content or None
    """
    if hasattr(vertex_output_data, "outputs") and vertex_output_data.outputs is not None:
        return vertex_output_data.outputs
    if hasattr(vertex_output_data, "results") and vertex_output_data.results is not None:
        return vertex_output_data.results
    if hasattr(vertex_output_data, "messages") and vertex_output_data.messages is not None:
        return vertex_output_data.messages
    if isinstance(vertex_output_data, dict):
        # Mirror the attribute order above so dict-form result data (the stream's
        # ``VertexBuildResponse.data``) resolves the same field as object-form
        # (sync's ``ResultData``), keeping sync/stream output content in parity.
        if vertex_output_data.get("outputs") is not None:
            return vertex_output_data["outputs"]
        if "results" in vertex_output_data:
            return vertex_output_data["results"]
        if "content" in vertex_output_data:
            return vertex_output_data["content"]
    return vertex_output_data


def _simplify_output_content(content: Any, output_type: str) -> Any:
    """Simplify output content for output nodes.

    For message types, extracts plain text from nested structures.
    For data/dataframe types, extracts the actual data value.
    For other types, returns content as-is.

    Args:
        content: The raw content
        output_type: The output type

    Returns:
        Simplified content
    """
    if not isinstance(content, dict):
        return content

    if output_type in {"message", "text"}:
        text = _extract_text_from_message(content)
        return text if text is not None else content

    if output_type == "data":
        # For data types, try multiple path combinations in order
        # This allows flexibility for different component output structures
        data_paths = [
            ("result", "message"),  # Standard: {'result': {'message': {...}}}
            ("results", "message"),  # Plural variant: {'results': {'message': {...}}}
        ]
        for path in data_paths:
            result_data = _extract_nested_value(content, *path)
            if result_data is not None:
                return result_data
    if output_type == "dataframe":
        # For dataframe types, try multiple path combinations in order
        dataframe_paths = [
            ("results", "message"),  # Plural: {'results': {'message': {...}}}
            ("result", "message"),  # Singular fallback: {'result': {'message': {...}}}
            ("run_sql_query", "message"),  # SQL component specific
        ]
        for path in dataframe_paths:
            dataframe_data = _extract_nested_value(content, *path)
            if dataframe_data is not None:
                return dataframe_data

    return content


def _build_metadata_for_non_output(
    raw_content: Any, vertex_id: str, vertex_display_name: str, vertex_type: str, output_type: str
) -> dict[str, Any]:
    """Build metadata for non-output terminal nodes.

    Extracts:
    - source: Model information for LLM components
    - file_path: File path for SaveToFile components

    Args:
        raw_content: The raw output data
        vertex_id: Vertex ID
        vertex_display_name: Vertex display name
        vertex_type: Vertex type
        output_type: Output type

    Returns:
        Metadata dict
    """
    metadata: dict[str, Any] = {}

    if output_type != "message" or not isinstance(raw_content, dict):
        return metadata

    # Extract model source for LLM components
    source_info = _extract_model_source(raw_content, vertex_id, vertex_display_name)
    if source_info:
        metadata["source"] = source_info

    # Extract file path for SaveToFile components
    file_path = _extract_file_path(raw_content, vertex_type)
    if file_path:
        metadata["file_path"] = file_path

    return metadata


def resolve_output_type(output_types: list[str] | None, vertex_type: str | None) -> str:
    """Resolve the v2 output ``type`` string from a vertex's declared output types.

    The single rule both the sync converter and the ``langflow`` stream adapter rely
    on so an output's ``type`` is identical in both modes: first declared output type
    lowercased, else the vertex type lowercased, else ``"unknown"``.
    """
    if output_types:
        first = output_types[0]
        if first:
            return first.lower()
    if vertex_type:
        return vertex_type.lower()
    return "unknown"


def build_component_output(
    *,
    component_id: str,
    is_output: bool,
    vertex_type: str | None,
    output_type: str,
    display_name: str | None,
    result_data: Any,
    valid: bool = True,
) -> ComponentOutput:
    """Build a ``ComponentOutput`` from one component's result data.

    Shared by the sync converter (``_process_terminal_vertex``) and the ``langflow``
    stream adapter so a component's output has the byte-identical shape in both modes.
    ``result_data`` is the per-component result — the sync ``ResultData`` object or the
    stream ``VertexBuildResponse.data`` dict; ``_get_raw_content`` tolerates both.

    The component id lives in the sync ``outputs`` dict key (and in ``OutputEvent`` on
    the stream), so ``ComponentOutput`` itself carries no component_id; the caller
    attaches it where needed.
    """
    metadata: dict[str, Any] = {"component_type": vertex_type}
    resolved_display_name = display_name or vertex_type

    content = None
    if result_data:
        raw_content = _get_raw_content(result_data)

        if is_output and raw_content is not None:
            # Output nodes: simplify content
            content = _simplify_output_content(raw_content, output_type)
        elif not is_output and raw_content is not None:
            # Non-output nodes:
            # - For data types: extract and show content
            # - For message types: extract metadata only (source, file_path)
            if output_type in ["data", "dataframe"]:
                content = _simplify_output_content(raw_content, output_type)
            else:
                metadata.update(
                    _build_metadata_for_non_output(
                        raw_content, component_id, resolved_display_name, vertex_type, output_type
                    )
                )

        # Add any additional metadata from result data
        if hasattr(result_data, "metadata") and result_data.metadata:
            metadata.update(result_data.metadata)
        elif isinstance(result_data, dict) and "metadata" in result_data:
            result_metadata = result_data.get("metadata")
            if isinstance(result_metadata, dict):
                metadata.update(result_metadata)

    # Derive per-component status instead of hardcoding COMPLETED so a client
    # trusting it is not given a false positive: a build that produced an error
    # artifact (``output_type == "error"``) or that the graph marked invalid is
    # FAILED. This mirrors the agui translator, which already keys node status on
    # the same ``valid`` flag, so sync and both stream protocols agree.
    status = JobStatus.FAILED if (output_type == "error" or not valid) else JobStatus.COMPLETED
    return ComponentOutput(
        type=output_type,
        status=status,
        display_name=resolved_display_name,
        content=content,
        metadata=metadata,
    )


def _process_terminal_vertex(
    vertex: Any,
    output_data_map: dict[str, Any],
) -> tuple[str, ComponentOutput]:
    """Process a single terminal vertex and return (output_key, component_output).

    Delegates the shape to ``build_component_output`` so sync and the stream adapter
    produce the identical ``ComponentOutput`` for the same component.

    Args:
        vertex: The vertex to process
        output_data_map: Map of component_id to output data

    Returns:
        Tuple of (output_key, ComponentOutput)
    """
    output_types = vertex.outputs[0].get("types", []) if (vertex.outputs and len(vertex.outputs) > 0) else []
    component_output = build_component_output(
        component_id=vertex.id,
        is_output=vertex.is_output,
        vertex_type=vertex.vertex_type,
        output_type=resolve_output_type(output_types, vertex.vertex_type),
        display_name=vertex.display_name or vertex.vertex_type,
        result_data=output_data_map.get(vertex.id),
    )
    return vertex.id, component_output


def _resolve_output(outputs: dict[str, ComponentOutput], selected_ids: list[str] | None = None) -> WorkflowOutput:
    """Resolve the run's primary text answer and explain why it resolved that way.

    ``text`` is the lone string answer only when exactly one output is a text
    channel (a ChatOutput/TextOutput with string content). Otherwise ``text`` is
    None and ``reason`` names why, so callers never have to guess which channel
    is "the answer":

    - ``single``: exactly one text answer (``text`` holds it, ``source`` names it)
    - ``multiple``: two or more text answers (read ``outputs`` and pick)
    - ``non_string``: a text channel exists but its content isn't a string
    - ``none``: no text channel at all (e.g. a data-only flow)

    ``selected_ids`` is the request-side ``output_ids`` selection. When given (and
    non-empty), resolution considers only the named outputs that this run actually
    produced (selected ∩ produced), so naming one ChatOutput on a multi-output flow
    yields ``single`` deterministically. Names that didn't fire this run (e.g. a
    branch not taken) are simply absent. ``outputs`` itself is never filtered — the
    selection steers ``output.text``, it does not hide outputs. An empty list means
    "no selection", same as None.

    An intentionally empty single answer is preserved as "" (distinct from None).
    The ``failed`` reason is set on the error path, not here.
    """
    considered = outputs
    if selected_ids:
        selected = set(selected_ids)
        considered = {component_id: output for component_id, output in outputs.items() if component_id in selected}
    text_items = [
        (component_id, output.content)
        for component_id, output in considered.items()
        if output.type in {"message", "text"} and isinstance(output.content, str)
    ]
    if len(text_items) == 1:
        component_id, text = text_items[0]
        return WorkflowOutput(reason=OutputReason.SINGLE, text=text, source=component_id)
    if text_items:
        # More than one text answer (exactly one was handled above).
        return WorkflowOutput(reason=OutputReason.MULTIPLE)
    # Zero string text answers: distinguish "a text channel exists but its
    # content isn't a string" from "no text channel at all".
    has_text_channel = any(output.type in {"message", "text"} for output in considered.values())
    reason = OutputReason.NON_STRING if has_text_channel else OutputReason.NONE
    return WorkflowOutput(reason=reason)


def run_response_to_workflow_response(
    run_response: RunResponse,
    flow_id: str,
    job_id: str,
    inputs: dict[str, Any],
    graph: Graph,
    effective_globals: dict[str, str] | None = None,
    selected_ids: list[str] | None = None,
) -> WorkflowExecutionResponse:
    """Convert V1 RunResponse to V2 WorkflowExecutionResponse.

    This function transforms the V1 execution response to the new V2 schema format.
    It intelligently handles different node types and determines what content to expose.

    Terminal Node Processing Logic:
        1. Identifies all terminal nodes (vertices with no successors)
        2. For each terminal node:
           - Output nodes (is_output=True): Full content is exposed
           - Data/DataFrame nodes: Content is exposed regardless of is_output flag
           - Message nodes (non-output): Only metadata is exposed (source, file_path)

    Output Key Selection:
        - Keys ``outputs`` by the stable ``vertex.id`` (component id), never the
          display name (a display-name alias would collide and break on rename).
        - ``display_name`` is carried as a field on each ``ComponentOutput`` for
          human-readable rendering.

    Args:
        run_response: The V1 response from simple_run_flow containing execution results
        flow_id: The flow identifier
        job_id: The generated job ID for tracking this execution
        inputs: Request inputs echoed back in the response
        graph: The Graph instance used for terminal node detection and vertex metadata
        effective_globals: The ``globals`` echoed in the response — the effective merged set
            (body globals plus any legacy header-supplied globals). When omitted, an empty
            globals map is echoed.
        selected_ids: The request-side ``output_ids`` selection. When set, ``output``
            resolves among only these component ids; ``outputs`` is unaffected.

    Returns:
        WorkflowExecutionResponse: V2 schema response with structured outputs

    Example:
        Terminal nodes: ["ChatOutput-abc", "LLM-xyz", "DataNode-123"]
        - ChatOutput-abc (is_output=True, type=message): Full content exposed
        - LLM-xyz (is_output=False, type=message): Only metadata (model source)
        - DataNode-123 (is_output=False, type=data): Full content exposed
    """
    # Get terminal nodes (vertices with no successors)
    try:
        terminal_node_ids = graph.get_terminal_nodes()
    except AttributeError:
        # Fallback: manually check successor_map
        terminal_node_ids = [vertex.id for vertex in graph.vertices if not graph.successor_map.get(vertex.id, [])]

    # Build output data map from run_response using component_id as key
    # This ensures unique keys even when components have duplicate display_names
    output_data_map: dict[str, Any] = {}
    if run_response.outputs:
        for run_output in run_response.outputs:
            if hasattr(run_output, "outputs") and run_output.outputs:
                for result_data in run_output.outputs:
                    if not result_data:
                        continue
                    # Use component_id as key to ensure uniqueness
                    component_id = result_data.component_id if hasattr(result_data, "component_id") else None
                    if component_id:
                        output_data_map[component_id] = result_data

    # Collect all terminal vertices
    terminal_vertices = [graph.get_vertex(vertex_id) for vertex_id in terminal_node_ids]

    # Process each terminal vertex
    outputs: dict[str, ComponentOutput] = {}
    for vertex in terminal_vertices:
        output_key, component_output = _process_terminal_vertex(vertex, output_data_map)
        outputs[output_key] = component_output

    response_globals = effective_globals if effective_globals is not None else {}

    return WorkflowExecutionResponse(
        flow_id=flow_id,
        session_id=run_response.session_id,
        job_id=job_id,
        object="response",
        status=JobStatus.COMPLETED,
        errors=[],
        inputs=inputs or {},
        globals=response_globals,
        output=_resolve_output(outputs, selected_ids=selected_ids),
        outputs=outputs,
    )


def create_job_response(job_id: str, flow_id: str) -> WorkflowJobResponse:
    """Create a background job response.

    Args:
        job_id: The generated job ID
        flow_id: The flow ID

    Returns:
        WorkflowJobResponse for background execution
    """
    return WorkflowJobResponse(
        job_id=job_id,
        flow_id=flow_id,
        created_timestamp=datetime.now(timezone.utc).isoformat(),
        status=JobStatus.QUEUED,
        errors=[],
    )


def create_error_response(
    flow_id: str,
    job_id: JobId,
    inputs: dict[str, Any],
    error: Exception,
    effective_globals: dict[str, str] | None = None,
) -> WorkflowExecutionResponse:
    """Create an error response in workflow format.

    Args:
        flow_id: The flow ID
        job_id: The job ID
        inputs: Request inputs echoed back in the response
        error: The exception that occurred
        effective_globals: Optional override for the ``globals`` echoed in the response.
            See :func:`run_response_to_workflow_response` for details.

    Returns:
        WorkflowExecutionResponse with error details
    """
    error_detail = ErrorDetail(
        error=str(error), code="EXECUTION_ERROR", details={"flow_id": flow_id, "error_type": type(error).__name__}
    )

    response_globals = effective_globals if effective_globals is not None else {}

    return WorkflowExecutionResponse(
        flow_id=flow_id,
        job_id=job_id,
        object="response",
        status=JobStatus.FAILED,
        errors=[error_detail],
        inputs=inputs or {},
        globals=response_globals,
        output=WorkflowOutput(reason=OutputReason.FAILED),
        outputs={},
    )
