"""LangFlow Components module."""

from __future__ import annotations

from typing import Any

from lfx.components import __all__ as _lfx_all

<<<<<<< HEAD
if TYPE_CHECKING:
    from langflow.components import (
        Notion,
        agentql,
        agents,
        aiml,
        amazon,
        anthropic,
        apify,
        arxiv,
        assemblyai,
        azure,
        baidu,
        bing,
        cleanlab,
        cloudflare,
        cohere,
        composio,
        confluence,
        crewai,
        custom_component,
        data,
        datastax,
        deepseek,
        docling,
        duckduckgo,
        embeddings,
        exa,
        firecrawl,
        git,
        glean,
        google,
        groq,
        helpers,
        homeassistant,
        huggingface,
        ibm,
        icosacomputing,
        input_output,
        langchain_utilities,
        langwatch,
        lmstudio,
        logic,
        maritalk,
        mem0,
        mistral,
        models,
        needle,
        notdiamond,
        novita,
        nvidia,
        olivya,
        ollama,
        openai,
        openrouter,
        perplexity,
        processing,
        redis,
        sambanova,
        scrapegraph,
        searchapi,
        serpapi,
        tavily,
        tools,
        twelvelabs,
        unstructured,
        vectorstores,
        vertexai,
        wikipedia,
        wolframalpha,
        xai,
        yahoosearch,
        youtube,
        zep,
    )

_dynamic_imports = {
    "agents": "langflow.components.agents",
    "data": "langflow.components.data",
    "processing": "langflow.components.processing",
    "vectorstores": "langflow.components.vectorstores",
    "tools": "langflow.components.tools",
    "models": "langflow.components.models",
    "embeddings": "langflow.components.embeddings",
    "helpers": "langflow.components.helpers",
    "input_output": "langflow.components.input_output",
    "logic": "langflow.components.logic",
    "custom_component": "langflow.components.custom_component",
    "openai": "langflow.components.openai",
    "anthropic": "langflow.components.anthropic",
    "google": "langflow.components.google",
    "azure": "langflow.components.azure",
    "huggingface": "langflow.components.huggingface",
    "ollama": "langflow.components.ollama",
    "groq": "langflow.components.groq",
    "cohere": "langflow.components.cohere",
    "mistral": "langflow.components.mistral",
    "deepseek": "langflow.components.deepseek",
    "nvidia": "langflow.components.nvidia",
    "amazon": "langflow.components.amazon",
    "vertexai": "langflow.components.vertexai",
    "xai": "langflow.components.xai",
    "perplexity": "langflow.components.perplexity",
    "openrouter": "langflow.components.openrouter",
    "lmstudio": "langflow.components.lmstudio",
    "sambanova": "langflow.components.sambanova",
    "maritalk": "langflow.components.maritalk",
    "novita": "langflow.components.novita",
    "olivya": "langflow.components.olivya",
    "notdiamond": "langflow.components.notdiamond",
    "needle": "langflow.components.needle",
    "cloudflare": "langflow.components.cloudflare",
    "baidu": "langflow.components.baidu",
    "aiml": "langflow.components.aiml",
    "ibm": "langflow.components.ibm",
    "langchain_utilities": "langflow.components.langchain_utilities",
    "crewai": "langflow.components.crewai",
    "composio": "langflow.components.composio",
    "mem0": "langflow.components.mem0",
    "datastax": "langflow.components.datastax",
    "cleanlab": "langflow.components.cleanlab",
    "langwatch": "langflow.components.langwatch",
    "icosacomputing": "langflow.components.icosacomputing",
    "homeassistant": "langflow.components.homeassistant",
    "agentql": "langflow.components.agentql",
    "assemblyai": "langflow.components.assemblyai",
    "twelvelabs": "langflow.components.twelvelabs",
    "docling": "langflow.components.docling",
    "unstructured": "langflow.components.unstructured",
    "redis": "langflow.components.redis",
    "zep": "langflow.components.zep",
    "bing": "langflow.components.bing",
    "duckduckgo": "langflow.components.duckduckgo",
    "serpapi": "langflow.components.serpapi",
    "searchapi": "langflow.components.searchapi",
    "tavily": "langflow.components.tavily",
    "exa": "langflow.components.exa",
    "glean": "langflow.components.glean",
    "yahoosearch": "langflow.components.yahoosearch",
    "apify": "langflow.components.apify",
    "arxiv": "langflow.components.arxiv",
    "confluence": "langflow.components.confluence",
    "firecrawl": "langflow.components.firecrawl",
    "git": "langflow.components.git",
    "wikipedia": "langflow.components.wikipedia",
    "youtube": "langflow.components.youtube",
    "scrapegraph": "langflow.components.scrapegraph",
    "Notion": "langflow.components.Notion",
    "wolframalpha": "langflow.components.wolframalpha",
}

__all__: list[str] = [
    "Notion",
    "agentql",
    "agents",
    "aiml",
    "amazon",
    "anthropic",
    "apify",
    "arxiv",
    "assemblyai",
    "azure",
    "baidu",
    "bing",
    "cleanlab",
    "cloudflare",
    "cohere",
    "composio",
    "confluence",
    "crewai",
    "custom_component",
    "data",
    "datastax",
    "deepseek",
    "docling",
    "duckduckgo",
    "embeddings",
    "exa",
    "firecrawl",
    "git",
    "glean",
    "google",
    "groq",
    "helpers",
    "homeassistant",
    "huggingface",
    "ibm",
    "icosacomputing",
    "input_output",
    "langchain_utilities",
    "langwatch",
    "lmstudio",
    "logic",
    "maritalk",
    "mem0",
    "mistral",
    "models",
    "needle",
    "notdiamond",
    "novita",
    "nvidia",
    "olivya",
    "ollama",
    "openai",
    "openrouter",
    "perplexity",
    "processing",
    "redis",
    "sambanova",
    "scrapegraph",
    "searchapi",
    "serpapi",
    "tavily",
    "tools",
    "twelvelabs",
    "unstructured",
    "vectorstores",
    "vertexai",
    "wikipedia",
    "wolframalpha",
    "xai",
    "yahoosearch",
    "youtube",
    "zep",
]
=======
__all__: list[str] = list(_lfx_all)
>>>>>>> main


def __getattr__(attr_name: str) -> Any:
    """Forward attribute access to lfx.components."""
    from lfx import components

    return getattr(components, attr_name)


def __dir__() -> list[str]:
    """Forward dir() to lfx.components."""
    return list(__all__)
