MAX_RETRY_ATTEMPTS = 5
INGESTION_BATCH_SIZE = 200
EXPONENTIAL_BACKOFF_MULTIPLIER = 2
MIN_KB_NAME_LENGTH = 3
CHUNK_PREVIEW_MULTIPLIER = 3

# KB deletion retry constants
MAX_DELETE_RETRIES = 5
DELETE_BACKOFF_SECONDS = 0.5
