```yaml
name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve Langflow
body:
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us, including Langflow version, platform, Python version, and any other relevant details.
      placeholder: Langflow version, platform, Python version, ...
    validations:
      required: true

  - type: textarea
    id: who-can-help
    attributes:
      label: Who can help?
      description: |
        Your issue will be replied to more quickly if you can figure out the right person to tag with @.
        If you know the relevant code owner, please tag them. Otherwise, leave this blank and a core maintainer will direct the issue accordingly.

        Please tag fewer than 3 people.

        Specific Areas:

          - Frontend: 
            - @anovazzi1
            - @Cristhianzl
            - @lucaseduoli
            - @igorrCarvalho
          - Backend: 
            - @ogabrielluiz
            - @italojohnny
          - Full Stack:
            - @nicoloboschi
            - @zzzming
            - @jordanrfrazier
            - @mfortman11
            - @NadirJ

      placeholder: "@Username ..."

  - type: checkboxes
    id: information-scripts-examples
    attributes:
      label: Information
      description: 'The problem arises when using:'
      options:
        - label: "The official example scripts"
        - label: "My own modified scripts"

  - type: checkboxes
    id: information-tasks
    attributes:
      label: Tasks
      description: "The tasks I am working on are:"
      options:
        - label: "An officially supported task in the `examples` folder"
        - label: "My own task or dataset (give details below)"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a code sample that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Do not use screenshots, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
```
