networks:
  dev-langflow:

services:
  langflow:
    build:
      context: ..
      dockerfile: docker/dev.sandbox.Dockerfile
    image: dev-langflow-sandbox
    container_name: dev-langflow-sandbox
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    privileged: true
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_SUPERUSER=langflow
      - LANGFLOW_SUPERUSER_PASSWORD=langflow
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-langflow


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    networks:
      -  dev-langflow