NEBIUS_MODELS = [
    "meta-llama/Meta-Llama-3.1-70B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "meta-llama/Llama-3.3-8B-Instruct",
    "meta-llama/Meta-Llama-3.1-405B-Instruct",
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
    "moonshotai/Kimi-K2-Instruct",
    "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    "NousResearch/Hermes-4-405B",
    "NousResearch/Hermes-4-70B",
    "zai-org/GLM-4.5",
    "zai-org/GLM-4.5-Air",
    "deepseek-ai/DeepSeek-R1-0528",
    "deepseek-ai/DeepSeek-R1",
    "deepseek-ai/DeepSeek-V3",
    "deepseek-ai/DeepSeek-V3-0324",
    "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "Qwen/Qwen3-235B-A22B",
    "Qwen/Qwen3-32B",
    "Qwen/Qwen3-30B-A3B",
    "Qwen/Qwen3-4B-fast",
    "Qwen/Qwen3-14B",
    "Qwen/Qwen2.5-Coder-7B",
    "Qwen/Qwen2.5-Coder-32B-Instruct",
    "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
    "mistralai/Mistral-Nemo-Instruct-2407",
    "google/gemma-2-2b-it",
]

MODEL_NAMES = NEBIUS_MODELS  # reverse compatibility
