name: "Setup uv"
description: "Checks out code, installs uv, and sets up Python environment"

inputs:
  python-version:
    description: "Python version to use"
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
