# Dockerfile for testing shell scripts
FROM alpine:3.21

# Install dependencies for testing
RUN apk add --no-cache \
    bash \
    curl \
    gettext \
    git \
    grep \
    jq \
    nginx \
    openssl \
    procps \
    shadow

# Install bats for testing
ARG BATS_VERSION=1.8.2
RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    git checkout v${BATS_VERSION} && \
    ./install.sh /usr/local && \
    cd .. && \
    rm -rf bats-core && \
    # Verify bats is working
    bats --version && \
    # Install bats support libraries
    git clone https://github.com/bats-core/bats-support.git /usr/local/lib/bats-support && \
    git clone https://github.com/bats-core/bats-assert.git /usr/local/lib/bats-assert

# Create the same directory structure as in the runtime container
RUN mkdir -p /etc/nginx/conf.d \
             /usr/share/nginx/html \
             /var/log/nginx \
             /nginx-access-log \
             /tmp/client_temp \
             /tmp/proxy_temp \
             /tmp/fastcgi_temp \
             /tmp/uwsgi_temp \
             /tmp/scgi_temp \
             /etc/nginx/extra-conf.d

# Create non-root user similar to the runtime container
RUN groupadd -g 10000 nginxuser && \
    useradd -u 10000 -g nginxuser -s /bin/bash -m nginxuser

# Set permissions
RUN chown -R 10000:10000 /nginx-access-log \
    /tmp/client_temp \
    /tmp/proxy_temp \
    /tmp/fastcgi_temp \
    /tmp/uwsgi_temp \
    /tmp/scgi_temp \
    /etc/nginx/extra-conf.d

# Create a directory for tests
WORKDIR /tests

# Don't copy files yet - they will be mounted at runtime

# Create the test runner script as a separate file
RUN echo '#!/bin/bash' > /run-tests.sh && \
    echo 'SCRIPT_PATH=${SCRIPT_PATH:-/start-nginx.sh}' >> /run-tests.sh && \
    echo 'CONFIG_TEMPLATE_PATH=${CONFIG_TEMPLATE_PATH:-/etc/nginx/conf.d/default.conf.template}' >> /run-tests.sh && \
    echo 'TESTS_PATH=${TESTS_PATH:-/tests/start-nginx-tests.bats}' >> /run-tests.sh && \
    echo '' >> /run-tests.sh && \
    echo '# Ensure scripts are executable' >> /run-tests.sh && \
    echo 'chmod +x "$SCRIPT_PATH"' >> /run-tests.sh && \
    echo 'chmod +x "$TESTS_PATH"' >> /run-tests.sh && \
    echo '' >> /run-tests.sh && \
    echo '# Print environment information' >> /run-tests.sh && \
    echo 'echo "Test Environment:"' >> /run-tests.sh && \
    echo 'echo "- Script path: $SCRIPT_PATH"' >> /run-tests.sh && \
    echo 'echo "- Config template path: $CONFIG_TEMPLATE_PATH"' >> /run-tests.sh && \
    echo 'echo "- Tests path: $TESTS_PATH"' >> /run-tests.sh && \
    echo '' >> /run-tests.sh && \
    echo 'echo "Running shell script tests..."' >> /run-tests.sh && \
    echo 'cd /tests' >> /run-tests.sh && \
    echo 'TERM=dumb bats $TESTS_PATH "$@"' >> /run-tests.sh && \
    chmod +x /run-tests.sh

# Set the default command to run tests
ENTRYPOINT ["/run-tests.sh"]
