from lfx.components._importing import import_mod

_dynamic_imports = {
    "PubrioBatchRedeemContactsComponent": "batch_redeem_contacts",
    "PubrioCreateMonitorComponent": "create_monitor",
    "PubrioDeleteMonitorComponent": "delete_monitor",
    "PubrioDuplicateMonitorComponent": "duplicate_monitor",
    "PubrioEnrichCompanyComponent": "enrich_company",
    "PubrioEnrichPersonComponent": "enrich_person",
    "PubrioFindSimilarCompaniesComponent": "find_similar_companies",
    "PubrioGetCompanySizesComponent": "get_company_sizes",
    "PubrioGetDepartmentFunctionsComponent": "get_department_functions",
    "PubrioGetDepartmentsComponent": "get_departments",
    "PubrioGetLocationsComponent": "get_locations",
    "PubrioGetManagementLevelsComponent": "get_management_levels",
    "PubrioGetMonitorChartComponent": "get_monitor_chart",
    "PubrioGetMonitorComponent": "get_monitor",
    "PubrioGetMonitorLogDetailComponent": "get_monitor_log_detail",
    "PubrioGetMonitorLogsComponent": "get_monitor_logs",
    "PubrioGetMonitorStatsComponent": "get_monitor_stats",
    "PubrioGetNewsCategoriesComponent": "get_news_categories",
    "PubrioGetNewsGalleriesComponent": "get_news_galleries",
    "PubrioGetNewsLanguagesComponent": "get_news_languages",
    "PubrioGetProfileComponent": "get_profile",
    "PubrioGetTimezonesComponent": "get_timezones",
    "PubrioGetUsageComponent": "get_usage",
    "PubrioGetUserComponent": "get_user",
    "PubrioLinkedInCompanyLookupComponent": "linkedin_company_lookup",
    "PubrioLinkedInPersonLookupComponent": "linkedin_person_lookup",
    "PubrioListMonitorsComponent": "list_monitors",
    "PubrioLookalikeLookupComponent": "lookalike_lookup",
    "PubrioLookupAdvertisementComponent": "lookup_advertisement",
    "PubrioLookupCompanyComponent": "lookup_company",
    "PubrioLookupJobComponent": "lookup_job",
    "PubrioLookupNewsComponent": "lookup_news",
    "PubrioLookupPersonComponent": "lookup_person",
    "PubrioQueryBatchRedeemComponent": "query_batch_redeem",
    "PubrioRetryMonitorComponent": "retry_monitor",
    "PubrioRevealContactComponent": "reveal_contact",
    "PubrioRevealMonitorSignatureComponent": "reveal_monitor_signature",
    "PubrioSearchAdsComponent": "search_ads",
    "PubrioSearchCompaniesComponent": "search_companies",
    "PubrioSearchJobsComponent": "search_jobs",
    "PubrioSearchNewsComponent": "search_news",
    "PubrioSearchPeopleComponent": "search_people",
    "PubrioSearchTechnologiesComponent": "search_technologies",
    "PubrioSearchTechnologyCategoriesComponent": "search_technology_categories",
    "PubrioSearchVerticalCategoriesComponent": "search_vertical_categories",
    "PubrioSearchVerticalSubCategoriesComponent": "search_vertical_sub_categories",
    "PubrioSearchVerticalsComponent": "search_verticals",
    "PubrioTechnologyLookupComponent": "lookup_technology",
    "PubrioTestRunMonitorComponent": "test_run_monitor",
    "PubrioUpdateMonitorComponent": "update_monitor",
    "PubrioValidateWebhookComponent": "validate_webhook",
}

__all__ = [
    "PubrioBatchRedeemContactsComponent",
    "PubrioCreateMonitorComponent",
    "PubrioDeleteMonitorComponent",
    "PubrioDuplicateMonitorComponent",
    "PubrioEnrichCompanyComponent",
    "PubrioEnrichPersonComponent",
    "PubrioFindSimilarCompaniesComponent",
    "PubrioGetCompanySizesComponent",
    "PubrioGetDepartmentFunctionsComponent",
    "PubrioGetDepartmentsComponent",
    "PubrioGetLocationsComponent",
    "PubrioGetManagementLevelsComponent",
    "PubrioGetMonitorChartComponent",
    "PubrioGetMonitorComponent",
    "PubrioGetMonitorLogDetailComponent",
    "PubrioGetMonitorLogsComponent",
    "PubrioGetMonitorStatsComponent",
    "PubrioGetNewsCategoriesComponent",
    "PubrioGetNewsGalleriesComponent",
    "PubrioGetNewsLanguagesComponent",
    "PubrioGetProfileComponent",
    "PubrioGetTimezonesComponent",
    "PubrioGetUsageComponent",
    "PubrioGetUserComponent",
    "PubrioLinkedInCompanyLookupComponent",
    "PubrioLinkedInPersonLookupComponent",
    "PubrioListMonitorsComponent",
    "PubrioLookalikeLookupComponent",
    "PubrioLookupAdvertisementComponent",
    "PubrioLookupCompanyComponent",
    "PubrioLookupJobComponent",
    "PubrioLookupNewsComponent",
    "PubrioLookupPersonComponent",
    "PubrioQueryBatchRedeemComponent",
    "PubrioRetryMonitorComponent",
    "PubrioRevealContactComponent",
    "PubrioRevealMonitorSignatureComponent",
    "PubrioSearchAdsComponent",
    "PubrioSearchCompaniesComponent",
    "PubrioSearchJobsComponent",
    "PubrioSearchNewsComponent",
    "PubrioSearchPeopleComponent",
    "PubrioSearchTechnologiesComponent",
    "PubrioSearchTechnologyCategoriesComponent",
    "PubrioSearchVerticalCategoriesComponent",
    "PubrioSearchVerticalSubCategoriesComponent",
    "PubrioSearchVerticalsComponent",
    "PubrioTechnologyLookupComponent",
    "PubrioTestRunMonitorComponent",
    "PubrioUpdateMonitorComponent",
    "PubrioValidateWebhookComponent"
]


def __getattr__(attr_name):
    if attr_name in _dynamic_imports:
        return import_mod(attr_name, _dynamic_imports[attr_name], __spec__)
    msg = f"module {__name__!r} has no attribute {attr_name!r}"
    raise AttributeError(msg)
