"""``lfx db`` -- drive lfx's own migration stream.

lfx does not migrate implicitly on ``serve`` (explicit-only policy): operators
provision the schema with these commands (or an init container / job) first.
They drive alembic directly against lfx's migration tree
(``lfx.services.database.migrations``, version table ``lfx_alembic_version``),
reading the database URL from settings (``LANGFLOW_DATABASE_URL``).
"""

from __future__ import annotations

import typer
from rich.console import Console

db_app = typer.Typer(
    name="db",
    help="Manage lfx's database schema (its own migration stream).",
    no_args_is_help=True,
)

_console = Console()
_err_console = Console(stderr=True)


def _config(stdout=None):
    """Build the alembic Config for lfx's stream from current settings."""
    from lfx.services.database.service import DatabaseService
    from lfx.services.deps import get_settings_service

    settings_service = get_settings_service()
    if settings_service is None:
        _err_console.print("[bold red]Error:[/bold red] settings service unavailable; cannot resolve database URL.")
        raise typer.Exit(1)
    try:
        return DatabaseService.make_cli_config(settings_service, stdout=stdout)
    except ValueError as exc:
        _err_console.print(f"[bold red]Error:[/bold red] {exc}")
        raise typer.Exit(1) from exc


@db_app.command(name="upgrade")
def upgrade(revision: str = typer.Argument("head", help="Target revision (default: head).")) -> None:
    """Apply migrations up to a revision (creates the schema on a fresh database)."""
    from alembic import command

    cfg = _config()
    try:
        command.upgrade(cfg, revision)
    except Exception as exc:
        _err_console.print(f"[bold red]Migration failed:[/bold red] {exc}")
        raise typer.Exit(1) from exc
    _console.print(f"[bold green]OK[/bold green] schema upgraded to {revision!r}.")


@db_app.command(name="downgrade")
def downgrade(revision: str = typer.Argument(..., help="Target revision, e.g. '-1' or a revision id.")) -> None:
    """Roll the schema back to a revision."""
    from alembic import command

    cfg = _config()
    try:
        command.downgrade(cfg, revision)
    except Exception as exc:
        _err_console.print(f"[bold red]Downgrade failed:[/bold red] {exc}")
        raise typer.Exit(1) from exc
    _console.print(f"[bold green]OK[/bold green] schema downgraded to {revision!r}.")


@db_app.command(name="current")
def current() -> None:
    """Show the current revision stamped in ``lfx_alembic_version``."""
    from alembic import command

    command.current(_config())


@db_app.command(name="check")
def check() -> None:
    """Fail (exit 1) if the models drift from the migrations. Use in CI."""
    from alembic import command
    from alembic.util import exc as alembic_exc

    cfg = _config()
    try:
        command.check(cfg)
    except alembic_exc.AutogenerateDiffsDetected as exc:
        _err_console.print(
            f"[bold red]Schema drift:[/bold red] models and migrations differ.\n{exc}\n"
            "Generate a revision with 'lfx db revision -m \"...\" --autogenerate' "
            "and land the equivalent change in langflow's stream."
        )
        raise typer.Exit(1) from exc
    except alembic_exc.CommandError as exc:
        _err_console.print(f"[bold red]Check failed:[/bold red] {exc} (is the schema migrated? run 'lfx db upgrade')")
        raise typer.Exit(1) from exc
    _console.print("[bold green]OK[/bold green] models match migrations.")


@db_app.command(name="revision")
def revision(
    message: str = typer.Option(..., "-m", "--message", help="Revision message."),
    autogenerate: bool = typer.Option(  # noqa: FBT001
        False,  # noqa: FBT003
        "--autogenerate",
        help="Diff models against the database to populate the revision.",
    ),
) -> None:
    """Create a new revision in lfx's migration stream."""
    from alembic import command

    cfg = _config()
    try:
        command.revision(cfg, message=message, autogenerate=autogenerate)
    except Exception as exc:
        _err_console.print(f"[bold red]Revision failed:[/bold red] {exc}")
        raise typer.Exit(1) from exc


def register(app: typer.Typer) -> None:
    """Register the ``db`` command group on the root lfx app."""
    app.add_typer(db_app, name="db", rich_help_panel="Database")
