export default {
	AzureChatOpenAI: {
		width: 384,
		height: 793,
		id: 'dndnode_7c07e36c-23cb-487e-b10c-719c63650e4e',
		type: 'genericNode',
		position: { x: 1136, y: 952 },
		data: {
			type: 'AzureChatOpenAI',
			node: {
				template: {
					verbose: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'verbose',
						advanced: false,
						type: 'bool',
						list: false,
					},
					callbacks: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'callbacks',
						advanced: false,
						type: 'langchain.callbacks.base.BaseCallbackHandler',
						list: true,
					},
					client: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'client',
						advanced: false,
						type: 'Any',
						list: false,
					},
					model_name: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: 'gpt-3.5-turbo',
						password: false,
						name: 'model_name',
						advanced: false,
						type: 'str',
						list: false,
					},
					temperature: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: 0.7,
						password: false,
						name: 'temperature',
						advanced: false,
						type: 'float',
						list: false,
					},
					model_kwargs: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						password: false,
						name: 'model_kwargs',
						advanced: true,
						type: 'code',
						list: false,
					},
					openai_api_key: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: '',
						password: true,
						name: 'openai_api_key',
						display_name: 'OpenAI API Key',
						advanced: false,
						type: 'str',
						list: false,
					},
					openai_api_base: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: '',
						password: true,
						name: 'openai_api_base',
						display_name: 'OpenAI API Base',
						advanced: false,
						type: 'str',
						list: false,
					},
					openai_organization: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: '',
						password: false,
						name: 'openai_organization',
						display_name: 'OpenAI Organization',
						advanced: false,
						type: 'str',
						list: false,
					},
					request_timeout: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'request_timeout',
						advanced: false,
						type: 'float',
						list: false,
					},
					max_retries: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: 6,
						password: false,
						name: 'max_retries',
						advanced: false,
						type: 'int',
						list: false,
					},
					streaming: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: false,
						password: false,
						name: 'streaming',
						advanced: false,
						type: 'bool',
						list: false,
					},
					n: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: 1,
						password: false,
						name: 'n',
						advanced: false,
						type: 'int',
						list: false,
					},
					max_tokens: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						password: true,
						name: 'max_tokens',
						advanced: false,
						type: 'int',
						list: false,
						value: '',
					},
					deployment_name: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: '',
						password: false,
						name: 'deployment_name',
						advanced: false,
						type: 'str',
						list: false,
					},
					openai_api_type: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: 'azure',
						password: false,
						name: 'openai_api_type',
						display_name: 'OpenAI API Type',
						advanced: false,
						type: 'str',
						list: false,
					},
					openai_api_version: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: '2023-03-15-preview',
						password: false,
						name: 'openai_api_version',
						display_name: 'OpenAI API Version',
						advanced: false,
						type: 'str',
						list: false,
					},
					_type: 'AzureChatOpenAI',
				},
				description:
					'Wrapper around Azure OpenAI Chat Completion API. To use this class you',
				base_classes: [
					'BaseChatModel',
					'ChatOpenAI',
					'BaseLanguageModel',
					'AzureChatOpenAI',
				],
				display_name: 'AzureChatOpenAI',
				targetHandleBase: ['BaseLanguageModel', 'llm'],
			},
			id: 'dndnode_7c07e36c-23cb-487e-b10c-719c63650e4e',
			value: null,
		},
		selected: false,
		dragging: false,
		positionAbsolute: { x: 1136, y: 952 },
	},
	LLMChain: {
		width: 384,
		height: 307,
		id: 'dndnode_1de39e70-9cda-4b41-b603-8a2b48a4b4ec',
		type: 'genericNode',
		position: { x: 1866.9000145655382, y: 963.5235249416831 },
		data: {
			type: 'LLMChain',
			node: {
				template: {
					memory: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						password: false,
						name: 'memory',
						advanced: false,
						type: 'BaseMemory',
						list: false,
					},
					callbacks: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'callbacks',
						advanced: false,
						type: 'langchain.callbacks.base.BaseCallbackHandler',
						list: true,
					},
					verbose: {
						required: false,
						placeholder: '',
						show: true,
						multiline: false,
						value: false,
						password: false,
						name: 'verbose',
						advanced: true,
						type: 'bool',
						list: false,
					},
					prompt: {
						required: true,
						placeholder: '',
						show: true,
						multiline: false,
						password: false,
						name: 'prompt',
						advanced: false,
						type: 'BasePromptTemplate',
						list: false,
					},
					llm: {
						required: true,
						placeholder: '',
						show: true,
						multiline: false,
						password: false,
						name: 'llm',
						advanced: false,
						type: 'BaseLanguageModel',
						list: false,
					},
					output_key: {
						required: true,
						placeholder: '',
						show: true,
						multiline: false,
						value: 'text',
						password: false,
						name: 'output_key',
						advanced: true,
						type: 'str',
						list: false,
					},
					_type: 'LLMChain',
				},
				description: 'Chain to run queries against LLMs.',
				base_classes: ['LLMChain', 'Chain', 'function'],
				display_name: 'LLMChain',
				targetHandleBase: [],
			},
			id: 'dndnode_1de39e70-9cda-4b41-b603-8a2b48a4b4ec',
			value: null,
		},
		selected: false,
		positionAbsolute: {
			x: 1866.9000145655382,
			y: 963.5235249416831,
		},
		dragging: false,
	},
	PromptTemplate: {
		width: 384,
		height: 265,
		id: 'dndnode_03e68de4-2f39-494d-b3de-71b7734abce6',
		type: 'genericNode',
		position: { x: 1147.5326973746678, y: 648.8785737648057 },
		data: {
			type: 'PromptTemplate',
			node: {
				template: {
					input_variables: {
						required: true,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'input_variables',
						advanced: false,
						type: 'str',
						list: true,
					},
					output_parser: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'output_parser',
						advanced: false,
						type: 'BaseOutputParser',
						list: false,
					},
					partial_variables: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						password: false,
						name: 'partial_variables',
						advanced: false,
						type: 'code',
						list: false,
					},
					template: {
						required: true,
						placeholder: '',
						show: true,
						multiline: true,
						password: false,
						name: 'template',
						advanced: false,
						type: 'prompt',
						list: false,
						value: '',
					},
					template_format: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: 'f-string',
						password: false,
						name: 'template_format',
						advanced: false,
						type: 'str',
						list: false,
					},
					validate_template: {
						required: false,
						placeholder: '',
						show: false,
						multiline: false,
						value: true,
						password: false,
						name: 'validate_template',
						advanced: false,
						type: 'bool',
						list: false,
					},
					_type: 'PromptTemplate',
				},
				description: 'Schema to represent a prompt for an LLM.',
				base_classes: [
					'BasePromptTemplate',
					'StringPromptTemplate',
					'PromptTemplate',
				],
				display_name: 'PromptTemplate',
				targetHandleBase: ['BasePromptTemplate', 'prompt'],
			},
			id: 'dndnode_03e68de4-2f39-494d-b3de-71b7734abce6',
			value: null,
		},
		selected: false,
		positionAbsolute: {
			x: 1147.5326973746678,
			y: 648.8785737648057,
		},
		dragging: false,
	},
};
