"""Check that all t("key") calls in the frontend source have entries in en.json.

Usage:
    python check_frontend_i18n_keys.py [--src SRC_DIR] [--en EN_JSON] [--report REPORT_FILE]

Exit code 1 if any keys are missing, 0 if all keys are present.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Pattern matches t("some.key") or t('some.key')
# Only captures keys that look like namespaced i18n keys (contain at least one dot)
KEY_PATTERN = re.compile(r"""[^a-zA-Z]t\(["']([a-zA-Z][a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_.]+)+)["']""")

EXTENSIONS = {".tsx", ".ts"}

# Keys that are dynamic or intentionally not in en.json
IGNORED_KEYS: set[str] = set()


def extract_keys_from_source(src_dir: Path) -> dict[str, list[str]]:
    """Return {key: [file:line, ...]} for all t() calls found in source files."""
    found: dict[str, list[str]] = {}
    for path in src_dir.rglob("*"):
        if path.suffix not in EXTENSIONS:
            continue
        if any(part.startswith("__") or part == "node_modules" or part == "__tests__" for part in path.parts):
            continue
        if path.name.endswith((".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx")):
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for lineno, line in enumerate(content.splitlines(), 1):
            for match in KEY_PATTERN.finditer(line):
                key = match.group(1)
                if key not in IGNORED_KEYS:
                    found.setdefault(key, []).append(f"{path}:{lineno}")
    return found


def load_en_json(en_json: Path) -> set[str]:
    with en_json.open(encoding="utf-8") as f:
        return set(json.load(f).keys())


def build_report(
    used_keys: dict[str, list[str]],
    en_keys: set[str],
    missing: dict[str, list[str]],
) -> str:
    en_total = len(en_keys)
    detected_total = len(used_keys)
    gap = en_total - detected_total
    status = "✅ All detected keys are present in `en.json`" if not missing else f"❌ {len(missing)} key(s) missing from `en.json`"

    lines = [
        "## Frontend i18n Key Coverage Report",
        "",
        f"### Status: {status}",
        "",
        "---",
        "",
        "### Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Keys in `en.json` | {en_total} |",
        f"| Statically detected `t()` keys in source | {detected_total} |",
        f"| Keys in source missing from `en.json` | {len(missing)} |",
        f"| Keys in `en.json` not found in source | {gap} |",
        "",
    ]

    if missing:
        lines += [
            "---",
            "",
            "### ❌ Missing Keys",
            "",
            "These keys are used in source files but have no entry in `en.json`.",
            "Add them to `src/frontend/src/locales/en.json` to fix this check.",
            "",
            "| Key | First occurrence |",
            "|-----|-----------------|",
        ]
        for key, locations in sorted(missing.items()):
            first = locations[0]
            lines.append(f"| `{key}` | `{first}` |")
        lines.append("")

    lines += [
        "---",
        "",
        "### ℹ️ Why `en.json` has more keys than detected in source",
        "",
        "The static analysis only counts hardcoded `t(\"some.key\")` string literals.",
        f"`en.json` has {en_total} keys while the scanner detected {detected_total} — a gap of {gap}. This is expected for three reasons:",
        "",
        "**1. Pluralization suffixes**",
        "",
        "i18next requires separate keys for singular/plural forms. When you write:",
        "```ts",
        "t(\"alerts.modelsRefreshed\", { count })",
        "```",
        "The source has one key, but `en.json` needs two:",
        "```json",
        "\"alerts.modelsRefreshed_one\": \"{{count}} model refreshed\",",
        "\"alerts.modelsRefreshed_other\": \"{{count}} models refreshed\"",
        "```",
        "",
        "**2. Dynamic keys**",
        "",
        "Some keys are built at runtime and cannot be statically detected:",
        "```ts",
        "t(item.display_name, { defaultValue: item.display_name })",
        "t(`component.${type}.label`)",
        "```",
        "",
        "**3. Test files excluded**",
        "",
        "Test files (`.test.tsx`, `.spec.tsx`, `__tests__/`) are excluded from scanning",
        "to avoid false positives from test data strings that happen to match the key pattern.",
        "",
        "---",
        "",
        "*Generated by `scripts/gp/check_frontend_i18n_keys.py`*",
    ]

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Check frontend i18n key coverage")
    parser.add_argument(
        "--src",
        default="src/frontend/src",
        help="Frontend source directory (default: src/frontend/src)",
    )
    parser.add_argument(
        "--en",
        default="src/frontend/src/locales/en.json",
        help="Path to en.json (default: src/frontend/src/locales/en.json)",
    )
    parser.add_argument(
        "--report",
        default=None,
        help="Path to write a markdown report file (optional)",
    )
    args = parser.parse_args()

    src_dir = Path(args.src)
    en_json = Path(args.en)

    if not src_dir.exists():
        print(f"ERROR: source directory not found: {src_dir}", file=sys.stderr)
        return 1
    if not en_json.exists():
        print(f"ERROR: en.json not found: {en_json}", file=sys.stderr)
        return 1

    used_keys = extract_keys_from_source(src_dir)
    en_keys = load_en_json(en_json)
    missing = {k: v for k, v in used_keys.items() if k not in en_keys}

    report = build_report(used_keys, en_keys, missing)

    if args.report:
        Path(args.report).write_text(report, encoding="utf-8")
        print(f"Report written to {args.report}")

    # Always print a summary to stdout
    if not missing:
        print(f"✓ All {len(used_keys)} detected i18n keys found in en.json")
        print(f"  (en.json has {len(en_keys)} total keys; gap of {len(en_keys) - len(used_keys)} is expected — see report for details)")
    else:
        print(f"✗ {len(missing)} key(s) used in source but missing from en.json:\n")
        for key, locations in sorted(missing.items()):
            print(f"  {key}")
            for loc in locations[:3]:
                print(f"    → {loc}")
            if len(locations) > 3:
                print(f"    → ... and {len(locations) - 3} more")
        print(f"\nAdd the missing keys to {en_json} and re-run.")

    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
