#! /bin/bash

poetry remove langchain
docker build -t logspace/backend_build -f build.Dockerfile .
VERSION=$(toml get --toml-path pyproject.toml tool.poetry.version)
docker build --build-arg VERSION=$VERSION -t logspace/langflow_backend:$VERSION .
# docker push logspace/langflow_backend:$VERSION
# poetry add --editable ../../../langchain
