#! /bin/bash

poetry remove langchain
docker build -t logspace/backend_build -f build.Dockerfile .
VERSION=$(toml get --toml-path pyproject.toml tool.poetry.version)
docker build --build-arg VERSION=$VERSION -t ibiscp/langflow_backend:$VERSION .
docker run -p 5003:80 -d ibiscp/langflow_backend:$VERSION
poetry add --editable ../../../langchain
