#!/usr/bin/env bash
set -euo pipefail

# wt.sh — manage dev containers for the main repo and git worktrees
#
# Each worktree gets a .wt-config file at its root (gitignored) that stores
# its container name, ports, and DB name. Generated once, reused on every
# subsequent call — same resources every time.
#
# Usage (run from the main repo or any worktree):
#   ./scripts/wt.sh up      start (or restart) this context's container
#   ./scripts/wt.sh down    stop container
#   ./scripts/wt.sh logs    follow logs
#   ./scripts/wt.sh status  show all running langflow containers
#   ./scripts/wt.sh config  print this context's saved config

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_REPO_PATH="$(git worktree list --porcelain | awk '/^worktree/{print $2; exit}')"
WT_PATH="$(git rev-parse --show-toplevel)"
CONFIG_FILE="$WT_PATH/.wt-config"
WT_COMPOSE="$MAIN_REPO_PATH/docker/worktree.docker-compose.yml"
DEV_COMPOSE="$MAIN_REPO_PATH/docker/dev.docker-compose.yml"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()   { echo "[wt] $*"; }
err()   { echo "[wt] ERROR: $*" >&2; exit 1; }

is_main() { [[ "$WT_PATH" == "$MAIN_REPO_PATH" ]]; }

# ── Port helper ───────────────────────────────────────────────────────────────
find_free_port() {
    local port=$1
    while docker ps --format '{{.Ports}}' 2>/dev/null | grep -q ":${port}->"; do
        port=$((port + 1))
    done
    echo "$port"
}

# ── Config ────────────────────────────────────────────────────────────────────
load_config() {
    [[ -f "$CONFIG_FILE" ]] || err "No .wt-config found. Run 'wt.sh up' to initialise."
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    log "Config: $WT_NAME | backend :$BACKEND_PORT | frontend :$FRONTEND_PORT | db $DB_NAME"
}

create_config() {
    local name
    name="$(basename "$WT_PATH" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/-\+/-/g; s/^-//; s/-$//')"

    local backend_port frontend_port
    backend_port="$(find_free_port 7861)"
    frontend_port="$(find_free_port 3001)"

    local db_name="langflow_wt_$(echo "$name" | tr '-' '_')"
    local container="langflow-wt-$name"

    local pg_network
    pg_network="$(docker inspect postgres --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}{{end}}' 2>/dev/null | awk '{print $1}')" \
        || err "Postgres container not found. Start it: docker compose -f docker/dev.docker-compose.yml up postgres -d"
    [[ -z "$pg_network" ]] && err "Could not determine postgres Docker network. Is the postgres container running?"

    cat > "$CONFIG_FILE" <<EOF
# Generated by wt.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Auto-managed fields below — do not edit manually.
WT_NAME=$name
CONTAINER_NAME=$container
BACKEND_PORT=$backend_port
FRONTEND_PORT=$frontend_port
DB_NAME=$db_name
POSTGRES_NETWORK=$pg_network

# Optional override: LLM endpoint for this worktree. Overrides .env in the
# container. Leave unset to auto-derive the docker gateway relay (:8484).
# OPENAI_BASE_URL=http://<gateway>:8484/v1
EOF
    log "Config saved → $CONFIG_FILE"
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
}

ensure_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$CONFIG_FILE"
        log "Loaded .wt-config: $WT_NAME | backend :$BACKEND_PORT | frontend :$FRONTEND_PORT | db $DB_NAME"
    else
        log "No .wt-config — generating for this worktree..."
        create_config
    fi
}

# ── Database ──────────────────────────────────────────────────────────────────
ensure_db() {
    local exists
    exists="$(docker exec postgres psql -U langflow -tAc \
        "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" 2>/dev/null | tr -d '[:space:]')"

    if [[ "$exists" == "1" ]]; then
        log "Database '$DB_NAME' already exists — skipping creation."
        return
    fi

    log "Creating database '$DB_NAME'..."
    docker exec postgres psql -U langflow -c "CREATE DATABASE \"$DB_NAME\" OWNER langflow;" > /dev/null

    log "Cloning schema from main langflow DB..."
    docker exec postgres pg_dump -U langflow --schema-only langflow \
        | docker exec -i postgres psql -U langflow -d "$DB_NAME" > /dev/null

    # Copy alembic_version rows so the app won't try to re-run already-applied migrations
    local version_count
    version_count="$(docker exec postgres psql -U langflow -tAc \
        "SELECT COUNT(*) FROM alembic_version" | tr -d '[:space:]')"
    if [[ "${version_count:-0}" -gt 0 ]]; then
        log "Copying alembic_version ($version_count row(s))..."
        docker exec postgres psql -U langflow -tAc \
            "COPY (SELECT version_num FROM alembic_version) TO STDOUT" \
            | docker exec -i postgres psql -U langflow -d "$DB_NAME" -c \
              "COPY alembic_version (version_num) FROM STDIN" > /dev/null
    fi

    log "Database '$DB_NAME' ready."
}

# ── LLM endpoint ────────────────────────────────────────────────────────────
# The LLM proxy binds to a host-only address that containers can't reach. A relay
# on the docker network gateway (host side) forwards :8484 to it. The container
# must therefore call the gateway, not the host's own address. We derive the
# gateway per machine so this stays portable; a worktree can override by setting
# OPENAI_BASE_URL in its .wt-config.
derive_llm_url() {
    if [[ -n "${OPENAI_BASE_URL:-}" ]]; then
        log "LLM endpoint (.wt-config override): $OPENAI_BASE_URL"
        return
    fi
    local gw
    gw="$(docker network inspect "$POSTGRES_NETWORK" --format '{{(index .IPAM.Config 0).Gateway}}' 2>/dev/null || true)"
    [[ -z "$gw" ]] && err "Could not derive gateway for network '$POSTGRES_NETWORK' (needed for LLM relay)."
    OPENAI_BASE_URL="http://${gw}:8484/v1"
    log "LLM endpoint (derived gateway relay): $OPENAI_BASE_URL"
}

# ── Worktree commands ─────────────────────────────────────────────────────────
wt_up() {
    ensure_config
    derive_llm_url
    export WT_NAME CONTAINER_NAME BACKEND_PORT FRONTEND_PORT DB_NAME POSTGRES_NETWORK WT_PATH MAIN_REPO_PATH OPENAI_BASE_URL
    ensure_db
    echo
    log "Starting $CONTAINER_NAME..."
    log "  Backend  → http://localhost:$BACKEND_PORT"
    log "  Frontend → http://localhost:$FRONTEND_PORT"
    echo
    docker compose --project-name "wt-${WT_NAME}" -f "$WT_COMPOSE" up -d
    log "Done. Tail logs: ./scripts/wt.sh logs"
}

wt_down() {
    load_config
    export WT_NAME CONTAINER_NAME BACKEND_PORT FRONTEND_PORT DB_NAME POSTGRES_NETWORK WT_PATH MAIN_REPO_PATH OPENAI_BASE_URL
    docker compose --project-name "wt-${WT_NAME}" -f "$WT_COMPOSE" down --remove-orphans
    log "Container stopped."
}

wt_logs() {
    load_config
    export WT_NAME CONTAINER_NAME BACKEND_PORT FRONTEND_PORT DB_NAME POSTGRES_NETWORK WT_PATH MAIN_REPO_PATH OPENAI_BASE_URL
    docker compose --project-name "wt-${WT_NAME}" -f "$WT_COMPOSE" logs -f
}

wt_config() {
    [[ -f "$CONFIG_FILE" ]] || err "No .wt-config in $WT_PATH. Run 'wt.sh up' first."
    cat "$CONFIG_FILE"
}

# ── Shared commands ───────────────────────────────────────────────────────────
cmd_status() {
    echo "Running langflow containers:"
    docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' \
        | grep -E 'NAMES|dev-langflow|langflow-wt' || echo "  (none)"
}

# ── Main ──────────────────────────────────────────────────────────────────────
CMD="${1:-up}"

# status works from anywhere
if [[ "$CMD" == "status" || "$CMD" == "ps" ]]; then
    cmd_status
    exit 0
fi

if is_main; then
    # Main repo — proxy to the standard dev compose
    case "$CMD" in
        up)     docker compose -f "$DEV_COMPOSE" up -d ;;
        down)   docker compose -f "$DEV_COMPOSE" down ;;
        logs)   docker compose -f "$DEV_COMPOSE" logs -f ;;
        config) log "Main repo — using docker/dev.docker-compose.yml (no .wt-config)." ;;
        *)      err "Unknown command '$CMD'. Use: up | down | logs | status | config" ;;
    esac
else
    # Worktree — use isolated container
    case "$CMD" in
        up)     wt_up ;;
        down)   wt_down ;;
        logs)   wt_logs ;;
        config) wt_config ;;
        *)      err "Unknown command '$CMD'. Use: up | down | logs | status | config" ;;
    esac
fi
