import errno
import os
import re
import shutil
import subprocess
import tempfile
import warnings
from pathlib import Path

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.operations import ops
from alembic.util.exc import AutogenerateDiffsDetected
from langflow.alembic.expand_compat import filter_expand_revision_directives, filter_sso_expand_diffs
from langflow.alembic.warning_filters import filter_known_sqlite_reflection_warnings
from langflow.services.database.service import SQLModel
from sqlalchemy import Column, String, Text, create_engine, inspect, text
from sqlalchemy.exc import SAWarning

_WORKSPACE_ROOT = Path(__file__).resolve().parents[5]
_SCRIPT_LOCATION = _WORKSPACE_ROOT / "src/backend/base/langflow/alembic"


def _make_alembic_cfg(db_url: str) -> Config:
    """Create an Alembic Config pointing at the project's migration scripts."""
    alembic_cfg = Config()

    if not _SCRIPT_LOCATION.exists():
        pytest.fail(f"Alembic script location not found at {_SCRIPT_LOCATION}")

    alembic_cfg.set_main_option("script_location", str(_SCRIPT_LOCATION))
    alembic_cfg.set_main_option("sqlalchemy.url", db_url)
    return alembic_cfg


# ---------------------------------------------------------------------------
# Database fixtures
# ---------------------------------------------------------------------------


def _normalize_pg_url(url: str) -> str:
    """Ensure a Postgres URL uses the psycopg (v3) async-capable driver.

    Alembic's env.py uses async_engine_from_config, which requires an
    async-capable dialect. The psycopg driver supports both sync and async.
    """
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    return url


def _pg_url() -> str | None:
    """Return a PostgreSQL URL from the environment, or None."""
    url = os.environ.get("LANGFLOW_TEST_DATABASE_URI")
    if url is not None:
        return _normalize_pg_url(url)
    return None


def _create_pg_test_database(base_url: str, db_name: str) -> str:
    """Create an isolated test database and return its URL."""
    engine = create_engine(base_url, isolation_level="AUTOCOMMIT")
    try:
        with engine.connect() as conn:
            conn.execute(
                text(
                    # db_name is generated internally from a hash, not user input
                    f"SELECT pg_terminate_backend(pid) FROM pg_stat_activity "  # noqa: S608
                    f"WHERE datname = '{db_name}' AND pid <> pg_backend_pid()"
                )
            )
            conn.execute(text(f"DROP DATABASE IF EXISTS {db_name}"))
            conn.execute(text(f"CREATE DATABASE {db_name}"))
    finally:
        engine.dispose()
    return base_url.rsplit("/", 1)[0] + f"/{db_name}"


def _drop_pg_test_database(base_url: str, db_name: str) -> None:
    """Drop the test database."""
    engine = create_engine(base_url, isolation_level="AUTOCOMMIT")
    try:
        with engine.connect() as conn:
            conn.execute(
                text(
                    # db_name is generated internally from a hash, not user input
                    f"SELECT pg_terminate_backend(pid) FROM pg_stat_activity "  # noqa: S608
                    f"WHERE datname = '{db_name}' AND pid <> pg_backend_pid()"
                )
            )
            conn.execute(text(f"DROP DATABASE IF EXISTS {db_name}"))
    finally:
        engine.dispose()


@pytest.fixture(params=["sqlite", "postgres"])
def db_url(request):
    """Parametrized fixture that yields a database URL for each backend."""
    if request.param == "sqlite":
        with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
            db_path = tmp.name
        yield f"sqlite+aiosqlite:///{db_path}"
        for suffix in ("", "-wal", "-shm", "-journal"):
            Path(db_path + suffix).unlink(missing_ok=True)
    else:
        base_url = _pg_url()
        if base_url is None:
            pytest.skip("LANGFLOW_TEST_DATABASE_URI not set")
        # Use a unique DB name per test to allow parallel execution
        import hashlib

        short_hash = hashlib.md5(request.node.name.encode()).hexdigest()[:10]  # noqa: S324
        db_name = f"lf_mig_test_{short_hash}"
        test_url = _create_pg_test_database(base_url, db_name)
        yield test_url
        _drop_pg_test_database(base_url, db_name)


def _parse_revision_values(line: str) -> list[str]:
    """Extract revision ID(s) from a line like ``revision: str = "abc123"``.

    Handles single strings, tuples of strings, and None.  Returns a list of
    zero or more revision ID strings.
    """
    if "=" not in line:
        return []
    raw = line.split("=", 1)[1]
    # Strip inline comments (e.g. "# pragma: allowlist secret")
    if "#" in raw:
        raw = raw[: raw.index("#")]
    raw = raw.strip()
    if raw == "None":
        return []
    # Extract all quoted strings from the value (handles both single values
    # and tuples like ("abc", "def"))
    return re.findall(r"""["']([a-f0-9]+)["']""", raw)


def _head_revision_at(ref: str) -> str | None:
    """Get the alembic head revision of the migration files at ``ref``.

    Uses ``git grep`` to read the ``revision`` and ``down_revision`` variables
    directly from the migration files at that ref, then walks the chain to find
    the head revision.  This avoids relying on filename conventions (which may
    not match the actual revision IDs inside the files) and works regardless of
    whether the branch adds, modifies, or deletes migration files.

    Returns None if git operations fail (e.g. shallow clone without origin/main).
    """
    git = shutil.which("git")
    if git is None:
        return None

    def _git_grep(pattern: str) -> str | None:
        try:
            result = subprocess.run(  # noqa: S603
                [
                    git,
                    "grep",
                    "-h",
                    pattern,
                    ref,
                    "--",
                    "src/backend/base/langflow/alembic/versions/",
                ],
                capture_output=True,
                text=True,
                check=True,
                cwd=_WORKSPACE_ROOT,
            )
        except subprocess.CalledProcessError:
            return None
        except OSError as exc:
            if exc.errno == errno.ENOENT:
                return None
            raise
        return result.stdout

    # Extract all revision IDs from the ref's migration files
    rev_output = _git_grep("^revision:")
    if not rev_output:
        return None

    rev_ids: set[str] = set()
    for line in rev_output.strip().splitlines():
        rev_ids.update(_parse_revision_values(line))

    if not rev_ids:
        return None

    # Extract all down_revision IDs to determine the chain
    down_output = _git_grep("^down_revision:")
    referenced: set[str] = set()
    if down_output:
        for line in down_output.strip().splitlines():
            referenced.update(_parse_revision_values(line))

    # Head = revisions not referenced as down_revision by any other revision
    heads = rev_ids - referenced

    if len(heads) == 1:
        return heads.pop()
    if len(heads) > 1:
        pytest.fail(f"{ref} has {len(heads)} head revisions — migration branches need merging: {heads}")
    return None


def _fork_point_with_main() -> str | None:
    """The commit this branch forked from ``origin/main`` (None if git cannot tell)."""
    git = shutil.which("git")
    if git is None:
        return None
    try:
        result = subprocess.run(  # noqa: S603
            [git, "merge-base", "HEAD", "origin/main"],
            capture_output=True,
            text=True,
            check=True,
            cwd=_WORKSPACE_ROOT,
        )
    except subprocess.CalledProcessError:
        return None
    except OSError as exc:
        if exc.errno == errno.ENOENT:
            return None
        raise
    return result.stdout.strip() or None


def _get_main_branch_head(branch_revisions: set[str] | None = None) -> str | None:
    """The revision an existing user's DB sits at before upgrading to this branch.

    Normally ``origin/main``'s alembic head. A PR based on a RELEASE branch, though,
    forked before some of main's migrations, so main's head is not in this branch's
    version directory at all and ``upgrade(main_head)`` can only raise "Can't locate
    revision". Pass ``branch_revisions`` to get the release-branch-aware answer: main's
    head AT THE FORK POINT (``git merge-base HEAD origin/main``), which is by
    construction reachable from this branch.

    This does not weaken the check for a branch that DELETES a migration main has: that
    revision exists at the fork point too, so the deletion still fails the upgrade.
    """
    main_head = _head_revision_at("origin/main")
    if main_head is None or branch_revisions is None or main_head in branch_revisions:
        return main_head
    fork_point = _fork_point_with_main()
    if fork_point is None:
        return main_head
    return _head_revision_at(fork_point) or main_head


def _filter_sqlite_noise(diffs: list) -> list:
    """Filter out diffs that are known SQLite limitations.

    - modify_nullable: SQLite doesn't support ALTER COLUMN
    - remove_fk/add_fk: SQLite doesn't track FK constraint names or actions
      (ondelete/onupdate), so autogenerate sees phantom FK diffs. Paired
      remove/add on the same (table, columns) with identical referenced targets
      are suppressed; unpaired or re-targeted FKs are preserved.
    """
    significant_diffs = []
    fk_removes: dict = {}  # (table, col_tuple) -> ForeignKeyConstraint
    fk_adds: dict = {}

    for d in diffs:
        if not (isinstance(d, tuple) and len(d) >= 2):
            significant_diffs.append(d)
            continue

        op_type = d[0]
        if op_type == "modify_nullable":
            continue
        if op_type in ("remove_fk", "add_fk"):
            fk = d[1]
            try:
                key = (fk.parent.name, tuple(sorted(c.name for c in fk.columns)))
            except (AttributeError, TypeError):
                significant_diffs.append(d)
                continue
            if op_type == "remove_fk":
                fk_removes[key] = fk
            else:
                fk_adds[key] = fk
            continue

        significant_diffs.append(d)

    # Compare FK remove/add pairs: suppress when referenced targets match.
    # We intentionally skip ondelete/onupdate comparison because SQLite's
    # PRAGMA foreign_key_list does not reliably report these actions.
    all_fk_keys = set(fk_removes) | set(fk_adds)
    for key in all_fk_keys:
        rm = fk_removes.get(key)
        add = fk_adds.get(key)
        if rm and add:
            rm_targets = sorted(
                (elem.column.table.name, elem.column.name) for elem in rm.elements if elem.column is not None
            )
            add_targets = sorted(
                (elem.column.table.name, elem.column.name) for elem in add.elements if elem.column is not None
            )
            if rm_targets and rm_targets == add_targets:
                continue  # Same target — name-only or action-only diff is SQLite noise
        if rm:
            significant_diffs.append(("remove_fk", rm))
        if add:
            significant_diffs.append(("add_fk", add))

    return significant_diffs


class _FakeColumn:
    """Minimal stand-in for sqlalchemy Column used by FK constraint diffs."""

    def __init__(self, name, table_name):
        self.name = name
        self.table = type("T", (), {"name": table_name})()


class _FakeElement:
    """Minimal stand-in for FK constraint element with a .column attribute."""

    def __init__(self, column):
        self.column = column


class _FakeFK:
    """Minimal stand-in for ForeignKeyConstraint used by autogenerate diffs."""

    def __init__(self, parent_table, col_names, ref_table, ref_col_names):
        self.parent = type("T", (), {"name": parent_table})()
        self.columns = [_FakeColumn(c, parent_table) for c in col_names]
        self.elements = [_FakeElement(_FakeColumn(rc, ref_table)) for rc in ref_col_names]


class TestFilterSqliteNoise:
    """Tests for _filter_sqlite_noise FK pair suppression logic."""

    def test_paired_fk_same_target_suppressed(self):
        """Paired remove_fk/add_fk on same columns with same target is noise."""
        fk_rm = _FakeFK("flow", ["user_id"], "user", ["id"])
        fk_add = _FakeFK("flow", ["user_id"], "user", ["id"])
        diffs = [("remove_fk", fk_rm), ("add_fk", fk_add)]
        assert _filter_sqlite_noise(diffs) == []

    def test_unpaired_remove_fk_preserved(self):
        """A remove_fk without matching add_fk is kept."""
        fk_rm = _FakeFK("flow", ["user_id"], "user", ["id"])
        diffs = [("remove_fk", fk_rm)]
        result = _filter_sqlite_noise(diffs)
        assert len(result) == 1
        assert result[0][0] == "remove_fk"

    def test_unpaired_add_fk_preserved(self):
        """An add_fk without matching remove_fk is kept."""
        fk_add = _FakeFK("flow", ["user_id"], "user", ["id"])
        diffs = [("add_fk", fk_add)]
        result = _filter_sqlite_noise(diffs)
        assert len(result) == 1
        assert result[0][0] == "add_fk"

    def test_paired_fk_different_target_preserved(self):
        """Paired remove_fk/add_fk pointing to different tables is a real change."""
        fk_rm = _FakeFK("flow", ["user_id"], "user", ["id"])
        fk_add = _FakeFK("flow", ["user_id"], "account", ["id"])
        diffs = [("remove_fk", fk_rm), ("add_fk", fk_add)]
        result = _filter_sqlite_noise(diffs)
        assert len(result) == 2

    def test_modify_nullable_always_suppressed(self):
        """modify_nullable diffs are always SQLite noise."""
        diffs = [("modify_nullable", "some_table", "some_col", {}, None, True)]
        assert _filter_sqlite_noise(diffs) == []

    def test_non_fk_diffs_preserved(self):
        """Non-FK diffs like add_column pass through unchanged."""
        diffs = [("add_column", "table", "col")]
        result = _filter_sqlite_noise(diffs)
        assert result == diffs


class TestFilterSsoExpandContractDiffs:
    """Keep the temporary SSO autogenerate exception narrow and directional."""

    def test_exact_legacy_remove_and_nullable_diffs_are_suppressed(self):
        legacy_column = _FakeColumn("provider", "sso_config")
        nullable_diff = (
            "modify_nullable",
            None,
            "sso_config",
            "provider_settings",
            {"existing_type": "JSON"},
            True,
            False,
        )

        assert filter_sso_expand_diffs([("remove_column", None, "sso_config", legacy_column), [nullable_diff]]) == []

    def test_other_tables_columns_and_nullable_directions_are_preserved(self):
        unrelated_column = _FakeColumn("provider", "another_table")
        inverse_nullable_diff = (
            "modify_nullable",
            None,
            "sso_config",
            "provider_settings",
            {"existing_type": "JSON"},
            False,
            True,
        )
        diffs = [
            ("remove_column", None, "another_table", unrelated_column),
            inverse_nullable_diff,
            ("modify_type", None, "sso_config", "provider_settings"),
        ]

        assert filter_sso_expand_diffs(diffs) == diffs

    def test_revision_hook_preserves_unrelated_and_grouped_changes(self):
        nullable_only = ops.AlterColumnOp(
            "sso_config",
            "slug",
            existing_type=String(),
            existing_nullable=True,
            modify_nullable=False,
        )
        nullable_and_type = ops.AlterColumnOp(
            "sso_config",
            "provider_settings",
            existing_type=String(),
            existing_nullable=True,
            modify_nullable=False,
            modify_type=Text(),
        )
        unrelated_nullable = ops.AlterColumnOp(
            "another_table",
            "slug",
            existing_type=String(),
            existing_nullable=True,
            modify_nullable=False,
        )
        unlisted_nullable = ops.AlterColumnOp(
            "sso_config",
            "enabled",
            existing_type=String(),
            existing_nullable=True,
            modify_nullable=False,
        )
        inverse_nullable = ops.AlterColumnOp(
            "sso_config",
            "slug",
            existing_type=String(),
            existing_nullable=False,
            modify_nullable=True,
        )
        unlisted_drop = ops.DropColumnOp.from_column_and_tablename(
            None,
            "sso_config",
            Column("unexpected", String()),
        )
        upgrade_ops = ops.UpgradeOps(
            [
                ops.ModifyTableOps(
                    "sso_config",
                    [
                        ops.DropColumnOp("sso_config", "provider"),
                        nullable_only,
                        nullable_and_type,
                        unlisted_drop,
                        unlisted_nullable,
                        inverse_nullable,
                    ],
                ),
                ops.ModifyTableOps("another_table", [unrelated_nullable]),
            ]
        )
        migration_script = ops.MigrationScript("test", upgrade_ops, ops.DowngradeOps([]))

        filter_expand_revision_directives(None, None, [migration_script])

        diffs = migration_script.upgrade_ops.as_diffs()
        flat_diffs = [diff for group in diffs for diff in (group if isinstance(group, list) else [group])]
        assert [diff[0] for diff in flat_diffs] == [
            "modify_type",
            "remove_column",
            "modify_nullable",
            "modify_nullable",
            "modify_nullable",
        ]
        assert flat_diffs[0][2:4] == ("sso_config", "provider_settings")
        assert flat_diffs[1][2] == "sso_config"
        assert flat_diffs[1][3].name == "unexpected"
        assert flat_diffs[2][2:4] == ("sso_config", "enabled")
        assert flat_diffs[3][2:4] == ("sso_config", "slug")
        assert flat_diffs[4][2:4] == ("another_table", "slug")
        assert migration_script.downgrade_ops.as_diffs() == migration_script.upgrade_ops.reverse().as_diffs()


def _engine_url(db_url: str) -> str:
    """Convert an async DB URL to a sync one for SQLAlchemy create_engine."""
    if db_url.startswith("sqlite+aiosqlite"):
        return db_url.replace("sqlite+aiosqlite", "sqlite", 1)
    return db_url


def _filter_diffs(diffs: list, db_url: str) -> list:
    """Apply documented compatibility and SQLite-specific diff filtering."""
    filtered_diffs = filter_sso_expand_diffs(diffs)
    if "sqlite" in db_url:
        filtered_diffs = _filter_sqlite_noise(filtered_diffs)
    return filtered_diffs


def test_no_phantom_migrations(db_url):
    """Verify that models and migrations are in sync.

    After migrating a fresh database to head, autogenerate should detect
    no additional changes. This catches cases where dependency upgrades
    (e.g. pydantic, sqlmodel) change how column metadata is emitted,
    which would produce unintended migration diffs.
    """
    alembic_cfg = _make_alembic_cfg(db_url)
    with warnings.catch_warnings(record=True) as migration_warnings:
        warnings.simplefilter("always", SAWarning)
        command.upgrade(alembic_cfg, "head")
        # Exercise the same Alembic autogenerate path used by DatabaseService at
        # application startup, including the active EXPAND compatibility hook.
        command.check(alembic_cfg)

    known_sqlite_reflection_warning = re.compile(
        r"^Skipped unsupported reflection of expression-based index "
        r"ix_message_session_metadata_(?:tenant|user)$"
    )
    assert not [
        warning
        for warning in migration_warnings
        if issubclass(warning.category, SAWarning) and known_sqlite_reflection_warning.fullmatch(str(warning.message))
    ]

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            migration_context = MigrationContext.configure(connection)
            with warnings.catch_warnings():
                if db_url.startswith("sqlite"):
                    filter_known_sqlite_reflection_warnings()
                diffs = compare_metadata(migration_context, SQLModel.metadata)
    finally:
        engine.dispose()

    significant_diffs = _filter_diffs(diffs, db_url)

    if significant_diffs:
        diff_descriptions = "\n".join(str(d) for d in significant_diffs)
        pytest.fail(
            f"Autogenerate detected {len(significant_diffs)} unexpected change(s) "
            f"after migrating to head. This likely means a dependency upgrade changed "
            f"how column metadata is generated.\n\nDiffs:\n{diff_descriptions}"
        )


def _create_foreign_tables(db_url: str) -> None:
    """Create the tables LangChain's PGVector store owns, as a tenant would."""
    engine = create_engine(_engine_url(db_url))
    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "CREATE TABLE langchain_pg_collection ("
                    "uuid VARCHAR NOT NULL PRIMARY KEY, "
                    "name VARCHAR NOT NULL, "
                    "cmetadata JSON)"
                )
            )
            connection.execute(
                text(
                    "CREATE TABLE langchain_pg_embedding ("
                    "id VARCHAR NOT NULL PRIMARY KEY, "
                    "collection_id VARCHAR REFERENCES langchain_pg_collection (uuid), "
                    "document VARCHAR, "
                    "cmetadata JSON)"
                )
            )
            connection.execute(text("CREATE INDEX ix_foreign_cmetadata ON langchain_pg_embedding (id)"))
    finally:
        engine.dispose()


def test_foreign_tables_do_not_block_startup(db_url):
    """Tables Langflow does not own must not be reported as pending drops.

    Langflow shares its database with whatever the user points at the same
    connection string -- LangChain vector stores, the SQL Executor component,
    unrelated applications. Autogenerate used to report each of those as a
    ``remove_table`` diff, so ``alembic check`` aborted startup with
    "There's a mismatch between the models and the database" (GH #9117).
    """
    alembic_cfg = _make_alembic_cfg(db_url)
    command.upgrade(alembic_cfg, "head")

    _create_foreign_tables(db_url)

    command.check(alembic_cfg)


def test_foreign_tables_do_not_hide_real_drift(db_url):
    """Filtering foreign tables must not silence drift in Langflow's own tables."""
    alembic_cfg = _make_alembic_cfg(db_url)
    command.upgrade(alembic_cfg, "head")

    _create_foreign_tables(db_url)

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.begin() as connection:
            connection.execute(text("ALTER TABLE flow ADD COLUMN unexpected_drift VARCHAR"))
    finally:
        engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected) as excinfo:
        command.check(alembic_cfg)

    assert "unexpected_drift" in str(excinfo.value)
    assert "langchain_pg" not in str(excinfo.value)


def test_create_all_then_upgrade_keeps_catalog_policy_empty(db_url):
    """Exercise fresh-install ordering without migration-authored data writes."""
    engine = create_engine(_engine_url(db_url))
    try:
        SQLModel.metadata.create_all(engine)
    finally:
        engine.dispose()

    alembic_cfg = _make_alembic_cfg(db_url)
    command.upgrade(alembic_cfg, "head")

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            row_count = connection.execute(text("SELECT count(*) FROM catalog_policy_rule")).scalar_one()
    finally:
        engine.dispose()

    assert row_count == 0


def test_message_ingestion_message_fk_repaired(db_url):
    """Repair the Postgres-only state left by concurrent startup migrations."""
    if not db_url.startswith("postgresql"):
        pytest.skip("PostgreSQL-only migration repair")

    alembic_cfg = _make_alembic_cfg(db_url)
    command.upgrade(alembic_cfg, "mb00a1b2c3d4")

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.begin() as connection:
            constraint_name = connection.execute(
                text(
                    """
                    SELECT conname
                    FROM pg_constraint
                    WHERE contype = 'f'
                      AND conrelid = 'message_ingestion_record'::regclass
                      AND confrelid = 'message'::regclass
                      AND conkey = ARRAY[
                          (
                              SELECT attnum
                              FROM pg_attribute
                              WHERE attrelid = 'message_ingestion_record'::regclass
                                AND attname = 'message_id'
                          )
                      ]::smallint[]
                    """
                )
            ).scalar_one()
            connection.execute(text(f'ALTER TABLE message_ingestion_record DROP CONSTRAINT "{constraint_name}"'))
    finally:
        engine.dispose()

    command.upgrade(alembic_cfg, "head")

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            restored_fk = connection.execute(
                text(
                    """
                    SELECT conname, confdeltype
                    FROM pg_constraint
                    WHERE contype = 'f'
                      AND conrelid = 'message_ingestion_record'::regclass
                      AND confrelid = 'message'::regclass
                      AND conkey = ARRAY[
                          (
                              SELECT attnum
                              FROM pg_attribute
                              WHERE attrelid = 'message_ingestion_record'::regclass
                                AND attname = 'message_id'
                          )
                      ]::smallint[]
                    """
                )
            ).one_or_none()
            assert restored_fk is not None
            assert restored_fk.confdeltype == "c"

            migration_context = MigrationContext.configure(connection)
            diffs = compare_metadata(migration_context, SQLModel.metadata)
    finally:
        engine.dispose()

    significant_diffs = _filter_diffs(diffs, db_url)
    assert significant_diffs == []


def test_upgrade_from_main_branch(db_url):
    """Verify that a DB at main's head can upgrade to current head and downgrade back.

    This catches the real-world scenario: a user running on main (or the latest release)
    upgrades to a branch with new migrations. The upgrade must succeed, the resulting
    schema must match the models, and downgrade back to main must also succeed.
    """
    from alembic.script import ScriptDirectory

    branch_cfg = Config()
    branch_cfg.set_main_option("script_location", str(_SCRIPT_LOCATION))
    branch_script = ScriptDirectory.from_config(branch_cfg)
    # The branch's own revisions decide whether main's head is even reachable here:
    # a release branch forked before main's latest migrations, so the upgrade has to
    # start from main's head AT THE FORK POINT instead. See _get_main_branch_head.
    branch_revisions = {script.revision for script in branch_script.walk_revisions()}

    main_head = _get_main_branch_head(branch_revisions)
    if main_head is None:
        if os.environ.get("MIGRATION_VALIDATION_CI"):
            pytest.fail("Could not determine main branch head revision — ensure fetch-depth: 0 and origin/main exists")
        pytest.skip("Could not determine main branch head revision (shallow clone or no origin/main)")

    # Check if main and branch share the same alembic head (no new migrations).
    # In that case this test is a no-op — alembic won't re-run already-applied
    # migrations, so upgrade(main_head) -> upgrade(head) does nothing.
    # Modified migrations are exercised by test_no_phantom_migrations instead.
    branch_heads = branch_script.get_heads()
    if len(branch_heads) == 1 and branch_heads[0] == main_head:
        pytest.skip(
            "No new migrations on this branch — main and branch share the same "
            "alembic head. Modified migrations are tested by test_no_phantom_migrations."
        )

    alembic_cfg = _make_alembic_cfg(db_url)

    # Step 1: Create DB at main's head revision (simulates existing user DB)
    command.upgrade(alembic_cfg, main_head)

    # Step 2: Upgrade to the current branch head
    command.upgrade(alembic_cfg, "head")

    # Step 3: Verify models match the migrated DB
    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            migration_context = MigrationContext.configure(connection)
            with warnings.catch_warnings():
                if db_url.startswith("sqlite"):
                    filter_known_sqlite_reflection_warnings()
                diffs = compare_metadata(migration_context, SQLModel.metadata)
    finally:
        engine.dispose()

    significant_diffs = _filter_diffs(diffs, db_url)

    if significant_diffs:
        diff_descriptions = "\n".join(str(d) for d in significant_diffs)
        pytest.fail(
            f"After upgrading from main ({main_head}) to head, "
            f"autogenerate detected {len(significant_diffs)} schema mismatch(es).\n\n"
            f"Diffs:\n{diff_descriptions}"
        )

    # Step 4: Downgrade back to main's head to verify rollback works
    command.downgrade(alembic_cfg, main_head)

    # Step 5: Verify the DB is back at main's revision after downgrade.
    # When the graph contains a merge revision joining main's lineage with a
    # release-branch lineage, downgrading across it "un-merges": alembic leaves
    # one version-table row per joined lineage (it only walks the branch that
    # contains the target), so get_current_revision() — which requires a single
    # head — would raise. Assert on get_current_heads() instead: main's head
    # must be current again, and the branch's own head must be unapplied.
    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            ctx = MigrationContext.configure(connection)
            current_heads = ctx.get_current_heads()
    finally:
        engine.dispose()

    assert main_head in current_heads, (
        f"After downgrade, expected revision {main_head} among current heads but got {current_heads}"
    )
    still_applied = set(branch_heads) & set(current_heads) - {main_head}
    assert not still_applied, f"Branch head(s) still applied after downgrade to {main_head}: {still_applied}"


def test_deployment_display_name_downgrade_restores_name_unique_constraint(db_url):
    """Downgrading the deployment display_name rename must restore the old name constraint."""
    alembic_cfg = _make_alembic_cfg(db_url)

    command.upgrade(alembic_cfg, "mb01b2c3d4e5")
    command.upgrade(alembic_cfg, "b7c4d8e9f012")  # pragma: allowlist secret
    command.downgrade(alembic_cfg, "mb01b2c3d4e5")

    engine = create_engine(_engine_url(db_url))
    try:
        with engine.connect() as connection:
            inspector = inspect(connection)
            column_names = {column["name"] for column in inspector.get_columns("deployment")}
            unique_constraints = inspector.get_unique_constraints("deployment")
    finally:
        engine.dispose()

    assert "name" in column_names
    assert "display_name" not in column_names
    assert any(
        constraint.get("name") == "uq_deployment_name_in_provider"
        and constraint.get("column_names") == ["deployment_provider_account_id", "name"]
        for constraint in unique_constraints
    )
