#! /bin/bash

# Read the contents of the JSON file
json=$(cat package.json)

# Extract the value of the "version" field using jq
VERSION=$(echo "$json" | jq -r '.version')

docker build -t logspace/frontend_build -f build.Dockerfile .
docker build --build-arg VERSION=$VERSION -t ibiscp/langflow_frontend:$VERSION .
docker push ibiscp/langflow_frontend:$VERSION
