name: Auto-update

on:
  push:
    branches:
      - main

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@4081c5bdc34560b58288a010318054e63e6f4a51 # v2
