name: Manual Cross-Platform Test

on:
  workflow_dispatch:
    inputs:
      test-from-pypi:
        description: "Test from PyPI instead of building from source"
        type: boolean
        default: false
      langflow-version:
        description: "Langflow version to test from PyPI (leave empty for latest)"
        required: false
        type: string
        default: ""
      test-timeout:
        description: "Timeout for langflow server startup test (minutes)"
        required: false
        type: number
        default: 5

jobs:
  test-pypi-installation:
    if: inputs.test-from-pypi == true
    name: Test PyPI Installation
    uses: ./.github/workflows/cross-platform-test-shared.yml
    with:
      install-method: "pypi"
      test-timeout: ${{ inputs.test-timeout }}
      langflow-version: ${{ inputs.langflow-version }}

  test-source-build:
    if: inputs.test-from-pypi == false
    name: Test Source Build and Install
    uses: ./.github/workflows/cross-platform-test.yml
    with:
      base-artifact-name: ""
      main-artifact-name: ""
      test-timeout: ${{ inputs.test-timeout }}

  test-summary:
    name: Test Summary
    needs: [test-pypi-installation, test-source-build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test-pypi-installation.result }}" = "failure" ] || [ "${{ needs.test-source-build.result }}" = "failure" ]; then
            echo "❌ Cross-platform tests failed"
            exit 1
          elif [ "${{ needs.test-pypi-installation.result }}" = "success" ] || [ "${{ needs.test-source-build.result }}" = "success" ]; then
            echo "✅ Cross-platform tests passed"
          else
            echo "ℹ️ No tests were run"
          fi