name: Docker Deploy - Entire Application

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select a Branch to deploy"
        required: true
        default: "main"
      domain:
        description: "Domain name for deployment"
        required: true
        default: "staging.visualaiagentsbuilder.com"
      email:
        description: "Admin email for deployment"
        required: true
        default: "saravana.k.r@gmail.com"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 \
          VITE_AUTO_LOGIN=false \
          VITE_CLERK_AUTH_ENABLED=true \
          VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} \
          make docker_build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: forwardemailforaifirstdesk
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Tag and Push Docker Image
        run: |
          docker tag langflow:1.4.2 forwardemailforaifirstdesk/langflow:1.4.2
          docker push forwardemailforaifirstdesk/langflow:1.4.2

      - name: Upload script to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: staging.visualaiagentsbuilder.com
          username: root
          password: ${{ secrets.VM_PASSWORD }}
          source: "./deploy/deploy.sh,./.env-file"
          target: /root/

      - name: Run script on VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: staging.visualaiagentsbuilder.com
          username: root
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            chmod +x /root/deploy/deploy.sh
            /root/deploy/deploy.sh \
              --image forwardemailforaifirstdesk/langflow:1.4.2 \
              --domain ${{ github.event.inputs.domain }} \
              --email ${{ github.event.inputs.email }} \
              --env-file /root/.env-file

  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Docker Hub Cleanup
        uses: docker-prune/action-docker-cleanup@v2
        with:
          repository: forwardemailforaifirstdesk/langflow
          keep-last: 2
          username: forwardemailforaifirstdesk
          password: ${{ secrets.DOCKER_HUB_TOKEN }}            