"""Tests for lfx's Tier 1 DatabaseService and its own migration stream.

These exercise the pieces that let a bare ``lfx serve`` provision and persist its
execution-history schema without langflow present:

* the migration mirror creates exactly the lfx-owned tables under
  ``lfx_alembic_version`` and does not drift from the models (``command.check``);
* the sync ``schema at head`` pre-flight the serve boot policy relies on;
* the Tier 2 ``DatabaseMemoryService`` round-trips over the real Tier 1 engine on
  the migration-provisioned schema.
"""

from __future__ import annotations

import io
import sqlite3
from typing import TYPE_CHECKING

import pytest
from alembic import command
from alembic.util import exc as alembic_exc
from lfx.schema.message import Message
from lfx.services.database.service import (
    DatabaseService,
    check_schema_at_head_sync,
)
from lfx.services.memory.database import DatabaseMemoryService

if TYPE_CHECKING:
    from pathlib import Path


@pytest.fixture
def db_settings(tmp_path, monkeypatch):
    """A real settings service pointed at a throwaway sqlite database."""
    db_file = tmp_path / "lfx_test.db"
    monkeypatch.setenv("LANGFLOW_DATABASE_URL", f"sqlite:///{db_file}")
    monkeypatch.setenv("LANGFLOW_ALEMBIC_LOG_TO_STDOUT", "true")

    from lfx.services.settings.service import SettingsService

    settings_service = SettingsService.initialize()
    # Stash the raw file path for assertions.
    settings_service._test_db_file = db_file  # type: ignore[attr-defined]
    return settings_service


def _upgrade(settings_service) -> None:
    cfg = DatabaseService.make_cli_config(settings_service, stdout=io.StringIO())
    command.upgrade(cfg, "head")


def _sqlite_tables(db_file: Path) -> set[str]:
    conn = sqlite3.connect(db_file)
    try:
        return {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    finally:
        conn.close()


def test_migration_mirror_creates_only_execution_tables(db_settings):
    """`lfx db upgrade` provisions exactly the lfx-owned tables + its version table."""
    _upgrade(db_settings)

    tables = _sqlite_tables(db_settings._test_db_file)
    assert {"message", "transaction", "vertex_build"} <= tables
    assert "lfx_alembic_version" in tables
    # No langflow-only tables leaked into lfx's stream.
    assert "flow" not in tables
    assert "user" not in tables
    assert "folder" not in tables


def test_version_table_is_lfx_specific(db_settings):
    """The lfx stream stamps its own version table, distinct from langflow's ``alembic_version``."""
    _upgrade(db_settings)
    conn = sqlite3.connect(db_settings._test_db_file)
    try:
        rows = list(conn.execute("SELECT version_num FROM lfx_alembic_version"))
    finally:
        conn.close()
    assert len(rows) == 1  # exactly one head stamped
    assert DatabaseService.alembic_version_table == "lfx_alembic_version"


def test_migration_check_reports_no_drift(db_settings):
    """The divergence guard: models match the migration (``command.check`` clean)."""
    _upgrade(db_settings)
    cfg = DatabaseService.make_cli_config(db_settings, stdout=io.StringIO())
    # Raises AutogenerateDiffsDetected if the migration lags the models.
    try:
        command.check(cfg)
    except alembic_exc.AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"Schema drift between models and lfx migration: {exc}")


def test_check_schema_at_head_sync_before_and_after(db_settings):
    """The fork-safe boot pre-flight flips from not-at-head to at-head after upgrade."""
    url = db_settings.settings.database_url
    script = DatabaseService.default_script_location()

    at_head, current, _head = check_schema_at_head_sync(
        url, script_location=script, version_table="lfx_alembic_version"
    )
    assert at_head is False
    assert current is None  # never migrated

    _upgrade(db_settings)

    at_head, current, head = check_schema_at_head_sync(url, script_location=script, version_table="lfx_alembic_version")
    assert at_head is True
    assert current == head is not None


async def test_database_memory_persists_over_real_service(db_settings):
    """Tier 2 memory round-trips over the real Tier 1 engine on the migrated schema."""
    import asyncio

    # The alembic runner calls asyncio.run() internally, so drive it off the
    # test's event loop in a worker thread (same pattern DatabaseService uses).
    await asyncio.to_thread(_upgrade, db_settings)

    db = DatabaseService(db_settings)
    try:
        memory = DatabaseMemoryService(database_service=db)
        stored = await memory.aadd_messages(
            [Message(text="persist me", sender="User", sender_name="alice", session_id="sess-1")]
        )
        assert len(stored) == 1

        got = await memory.aget_messages(session_id="sess-1")
        assert len(got) == 1
        assert got[0].text == "persist me"
        assert got[0].sender_name == "alice"
    finally:
        await db.teardown()


def test_capabilities_and_tier():
    """The real DatabaseService advertises Tier 1 + PERSISTENT."""
    from lfx.services.capabilities import Capability, Tier

    assert DatabaseService.tier == Tier.INFRASTRUCTURE
    assert Capability.PERSISTENT in DatabaseService.capabilities
