"""Canonical xyflow diagram schema + validator (Story 2.2).

Lothal went xyflow-only: there is no Mermaid and no conversion step. The diagram
*is* an xyflow graph (nodes-with-positions + edges) end to end — generated by the
model (Story 2.1), edited on the B.4 canvas, and persisted verbatim to
`lothal_project.diagram_json`. This module is the single source of truth for that
graph's shape and what makes it valid.

Everything here is a pure function with no DB or LLM dependency, so generation
(2.1) and refinement (Epic 3) can both gate their output through the same
`validate_diagram` without pulling in those layers. The Pydantic models enforce
structure (known node types, numeric positions, an edge order); `validate_diagram`
adds the cross-field rules a single model can't see — unique ids, edges that point
at real nodes, and the minimum graph size a sequence diagram needs to be useful.

Position *repair* (cramped/overlapping/missing coordinates) is deliberately not
here — that is the `auto_layout` safety net (Story 2.5). This module only judges
validity; it never moves a node.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

# A sequence diagram needs at least two participants exchanging at least a few
# messages to be worth rendering; below this it is almost certainly a bad
# generation, so the validator rejects it and lets the caller retry.
MIN_NODES = 2
MIN_EDGES = 3

NodeType = Literal["actorNode", "systemNode"]


class DiagramValidationError(ValueError):
    """A diagram graph is structurally or semantically invalid.

    Raised by `validate_diagram` for both Pydantic-level shape errors (wrong node
    type, missing position/order) and the cross-field rules (duplicate ids,
    dangling edges, too few nodes/edges). Subclasses `ValueError`, so callers can
    catch either type.
    """


class DiagramNodeData(BaseModel):
    """Node payload. `label` is the only guaranteed field.

    `kind` (person/service/ui/data) and `note` are optional render hints the
    generator may add; extra keys are tolerated so the contract can grow without
    breaking older stored graphs.
    """

    model_config = ConfigDict(extra="allow")

    label: str
    kind: str | None = None
    note: str | None = None


class NodePosition(BaseModel):
    """Canvas coordinates. Required and numeric on every node.

    Garbage values (overlapping, off-canvas) are *not* rejected here — repairing
    them is `auto_layout`'s job (Story 2.5); this only guarantees the field is
    present and numeric.
    """

    x: float
    y: float


class DiagramNode(BaseModel):
    """An xyflow node — an `actorNode` (person/external) or `systemNode` (service)."""

    id: str
    type: NodeType
    position: NodePosition
    data: DiagramNodeData


class DiagramEdgeData(BaseModel):
    """Edge payload. `order` is the sequence index; `label`/`kind` are render hints."""

    model_config = ConfigDict(extra="allow")

    order: int
    label: str | None = None
    kind: str | None = None


class DiagramEdge(BaseModel):
    """A directed message between two nodes.

    `animated` mirrors the message style: `False` = synchronous (solid), `True` =
    asynchronous/return (dashed).
    """

    id: str
    source: str
    target: str
    animated: bool = False
    data: DiagramEdgeData


class DiagramGraph(BaseModel):
    """The full xyflow graph: nodes-with-positions plus ordered edges.

    This is exactly what is stored in `diagram_json` and returned by `/diagram`.
    The model enforces per-item shape; `validate_diagram` enforces the graph-wide
    rules (unique ids, referential integrity, minimum size).
    """

    nodes: list[DiagramNode] = Field(default_factory=list)
    edges: list[DiagramEdge] = Field(default_factory=list)


def validate_diagram(graph: Any) -> DiagramGraph:
    """Validate an xyflow graph, returning the parsed `DiagramGraph` or raising.

    Accepts a `DiagramGraph`, a plain dict, or anything Pydantic can coerce, so
    callers can pass raw LLM output straight in. Raises `DiagramValidationError`
    with a specific message for the first problem found:

    - malformed shape (unknown node type, missing position, missing edge order);
    - duplicate node ids;
    - an edge whose `source`/`target` does not name an existing node;
    - fewer than `MIN_NODES` nodes or `MIN_EDGES` edges.

    The structural checks run first (via the Pydantic models), then the
    cross-field rules a single model can't express.
    """
    try:
        parsed = graph if isinstance(graph, DiagramGraph) else DiagramGraph.model_validate(graph)
    except ValidationError as exc:
        msg = f"Malformed diagram graph: {exc}"
        raise DiagramValidationError(msg) from exc

    if len(parsed.nodes) < MIN_NODES:
        msg = f"Diagram needs at least {MIN_NODES} nodes, got {len(parsed.nodes)}."
        raise DiagramValidationError(msg)
    if len(parsed.edges) < MIN_EDGES:
        msg = f"Diagram needs at least {MIN_EDGES} edges, got {len(parsed.edges)}."
        raise DiagramValidationError(msg)

    node_ids = [node.id for node in parsed.nodes]
    seen: set[str] = set()
    duplicates = {nid for nid in node_ids if nid in seen or seen.add(nid)}
    if duplicates:
        msg = f"Duplicate node id(s): {', '.join(sorted(duplicates))}."
        raise DiagramValidationError(msg)

    known = set(node_ids)
    for edge in parsed.edges:
        missing = [end for end in (edge.source, edge.target) if end not in known]
        if missing:
            msg = f"Edge {edge.id!r} references unknown node(s): {', '.join(missing)}."
            raise DiagramValidationError(msg)

    return parsed
